# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
import adminServices
import homePage

conn = sqlite3.connect('taxi.db')   # creates the actual database
c = conn.cursor()  # The cursor to take data to and from the database.

class Ui_adminLoginScreen_Dialog(object):
    def __init__(self, Dialog):  # creation of a constructor
        self.Dialog = QtWidgets.QDialog()   # this class has one attribute
        self.adminLoginScreen_setupUi(self.Dialog)  # attribute is need to setup the ui

    def its_showtime(self):   # used to show the dialog
        self.Dialog.show()

    def its_closetime(self):  # used to close the dialog
        self.Dialog.close()

    def adminBack_clicked(self):
        self.dialog = QtWidgets.QDialog()     # goes back to the Home Page
        hP = homePage.Ui_homeScreen_Dialog(self.dialog)
        hP.its_showtime()
        self.its_closetime()

    def adminLogin_clicked(self):
        if  self.adminPassword_txt.text() and self.adminEmail_txt.text() == \
            self.adminEmail_txt.text() in self.get_admin_info().__str__() and \
            self.adminPassword_txt.text() in self.get_admin_info().__str__():
            self.successfull_login_msg("Congratulations, your login credentials is correct. Enjoy!!")
            self.dialog = QtWidgets.QDialog()   # open the admin Services screen for positive login.
            aS = adminServices.Ui_adminPortal_Dialog(self.dialog)
            aS.its_showtime()
            self.its_closetime()
        else:
            self.failed_login_message("Incorrect Login Credentials!")

    def get_admin_info(self):
        c.execute("SELECT * FROM Admin WHERE email=:email",
                  {'email': self.adminEmail_txt.text()})
        return c.fetchall()  # returns the password from the database

    def successfull_login_msg(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Notification.")
        msg.setInformativeText(message)
        msg.setWindowTitle("Congratulations")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def failed_login_message(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Notification.")
        msg.setInformativeText(message)
        msg.setWindowTitle("Notification")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def adminLoginScreen_setupUi(self, adminLoginScreen_Dialog):
        adminLoginScreen_Dialog.setObjectName("adminLoginScreen_Dialog")
        adminLoginScreen_Dialog.resize(671, 460)
        self.adminLoginScreen = QtWidgets.QWidget(adminLoginScreen_Dialog)
        self.adminLoginScreen.setGeometry(QtCore.QRect(10, 10, 651, 441))
        self.adminLoginScreen.setStyleSheet("border: 8px solid black;\n"
    "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255),"
    " stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n""")
        self.adminLoginScreen.setObjectName("adminLoginScreen")
        self.adminLoginBtn = QtWidgets.QPushButton(self.adminLoginScreen,
                                                   clicked=lambda: self.adminLogin_clicked())
        self.adminLoginBtn.setGeometry(QtCore.QRect(310, 300, 101, 31))
        self.adminLoginBtn.setStyleSheet("background-color: rgb(255, 0, 127);\n"
    "border: 3px solid #0029FF;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 12px;\n"
    "text-align: center;\n"
    "color: white;")
        self.adminLoginBtn.setObjectName("adminLoginBtn")
        self.adminEmail_txt = QtWidgets.QLineEdit(self.adminLoginScreen)
        self.adminEmail_txt.setGeometry(QtCore.QRect(260, 240, 221, 20))
        self.adminEmail_txt.setStyleSheet("background: #C4C4C4;\n"
    "border: 2px solid blue;")
        self.adminEmail_txt.setObjectName("adminEmail_txt")
        self.adminPassword_txt = QtWidgets.QLineEdit(self.adminLoginScreen)
        self.adminPassword_txt.setGeometry(QtCore.QRect(260, 270, 221, 20))
        self.adminPassword_txt.setStyleSheet("background: #C4C4C4;\n"
    "border: 2px solid blue;")
        self.adminPassword_txt.setObjectName("adminPassword_txt")
        self.adminPassword_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email_label = QtWidgets.QLabel(self.adminLoginScreen)
        self.email_label.setGeometry(QtCore.QRect(170, 240, 51, 16))
        self.email_label.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 15px;\n"
    "text-align: center;\n"
    "color: #000000;\n"
    "border: none;\n"
    "background-color:none;")
        self.email_label.setObjectName("email_label")
        self.password_label = QtWidgets.QLabel(self.adminLoginScreen)
        self.password_label.setGeometry(QtCore.QRect(170, 270, 81, 16))
        self.password_label.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 15px;\n"
    "text-align: center;\n"
    "color: #000000;\n"
    "border: none;\n"
    "background-color:none;")
        self.password_label.setObjectName("password_label")
        self.adminLoginLabel = QtWidgets.QLabel(self.adminLoginScreen)
        self.adminLoginLabel.setGeometry(QtCore.QRect(260, 190, 141, 21))
        self.adminLoginLabel.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 18px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "background-color:none;")
        self.adminLoginLabel.setObjectName("adminLoginLabel")
        self.adminBackBtn = QtWidgets.QPushButton(self.adminLoginScreen,
                                                    clicked=lambda: self.adminBack_clicked())
        self.adminBackBtn.setGeometry(QtCore.QRect(540, 390, 91, 31))
        self.adminBackBtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 13px;\n"
    "text-align: center;\n"
    "color: white;")
        self.adminBackBtn.setObjectName("adminBackBtn")
        self.border = QtWidgets.QLabel(self.adminLoginScreen)
        self.border.setGeometry(QtCore.QRect(70, 170, 511, 201))
        self.border.setStyleSheet("border: 3.5px dotted red;\n"
    "background-color:none;\n""")
        self.border.setText("")
        self.border.setObjectName("border")
        self.slogan = QtWidgets.QLabel(self.adminLoginScreen)
        self.slogan.setGeometry(QtCore.QRect(160, 110, 331, 41))
        self.slogan.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "color: white;\n"
    "background-color:none;")
        self.slogan.setObjectName("slogan")
        self.logo = QtWidgets.QLabel(self.adminLoginScreen)
        self.logo.setGeometry(QtCore.QRect(270, 10, 111, 101))
        self.logo.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.border.raise_()
        self.adminLoginBtn.raise_()
        self.adminEmail_txt.raise_()
        self.adminPassword_txt.raise_()
        self.email_label.raise_()
        self.password_label.raise_()
        self.adminLoginLabel.raise_()
        self.adminBackBtn.raise_()
        self.slogan.raise_()
        self.logo.raise_()

        self.retranslateUi(adminLoginScreen_Dialog)
        QtCore.QMetaObject.connectSlotsByName(adminLoginScreen_Dialog)

    def retranslateUi(self, adminLoginScreen_Dialog):
        _translate = QtCore.QCoreApplication.translate
        adminLoginScreen_Dialog.setWindowTitle(_translate("adminLoginScreen_Dialog", "Dialog"))
        self.adminLoginBtn.setText(_translate("adminLoginScreen_Dialog", "LOGIN"))
        self.email_label.setText(_translate("adminLoginScreen_Dialog", "Email"))
        self.password_label.setText(_translate("adminLoginScreen_Dialog", "Password"))
        self.adminLoginLabel.setText(_translate("adminLoginScreen_Dialog",
         "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">ADMIN LOGIN"
         "</span></p></body></html>"))
        self.adminBackBtn.setText(_translate("adminLoginScreen_Dialog", "BACK"))
        self.slogan.setText(_translate("adminLoginScreen_Dialog", "<html><head/><body><p align=\"center\">"
         "<span style=\" font-size:11pt;\">Dear Admins, always remember together <br>we acheive more!!</span>"
         "</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminLoginScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_adminLoginScreen_Dialog()
    ui.adminLoginScreen_setupUi(adminLoginScreen_Dialog)
    adminLoginScreen_Dialog.show()
    sys.exit(app.exec_())
