# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminServices.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import adminRegister
import driverRegister
import  driverForgotPasswordScreen
import  adminForgotPasswordScreen
import confirmBooking
import assignBooking
import homePage


class Ui_adminPortal_Dialog(object):
    def __init__(self, Dialog):      # creation of a constructor
        self.Dialog = QtWidgets.QDialog()    # this class has one attribute
        self.adminPortal_setupUi(self.Dialog)    # attribute is need to setup the ui

    def its_showtime(self):   # used to show the dialog
        self.Dialog.show()

    def its_closetime(self):   # used to close the dialog
        self.Dialog.close()

    def logout_clicked(self):    # goes back to the Home Screen.
        self.dialog = QtWidgets.QDialog()
        hP = homePage.Ui_homeScreen_Dialog(self.dialog)
        hP.its_showtime()
        self.its_closetime()

    def adminRegister_clicked(self):    # open the admin registration screen
        self.dialog = QtWidgets.QDialog()
        aR = adminRegister.Ui_adminRegisterScreen_Dialog(self.dialog)
        aR.its_showtime()
        self.its_closetime()

    def driverRegister_clicked(self):    # open the driver registration screen
        self.dialog = QtWidgets.QDialog()
        dR = driverRegister.Ui_driverRegisterScreen_Dialog(self.dialog)
        dR.its_showtime()
        self.its_closetime()

    def driverForgotPassword_button_click(self):   # open the driver forgot password registration screen
                self.dialog = QtWidgets.QDialog()
                dFP = driverForgotPasswordScreen.Ui_driverForgotPasswordScreen_Dialog(self.dialog)
                dFP.its_showtime()
                self.its_closetime()

    def adminForgotPassword_clicked(self):   # open the admin forgot password registration screen
        self.dialog = QtWidgets.QDialog()
        aFP = adminForgotPasswordScreen.Ui_adminForgotPasswordScreen_Dialog(self.dialog)
        aFP.its_showtime()
        self.its_closetime()

    def confirmBooking_clicked(self):   # open the confirm booking screen
        self.dialog = QtWidgets.QDialog()
        cB = confirmBooking.Ui_confirmBookingScreen_Dialog(self.dialog)
        cB.its_showtime()
        self.its_closetime()

    def assignDriver_clicked(self):   # open the assign driver screen
        self.dialog = QtWidgets.QDialog()
        aB = assignBooking.Ui_assignBookingScreen_Dialog(self.dialog)
        aB.its_showtime()
        self.its_closetime()

    def adminPortal_setupUi(self, adminPortal_Dialog):
        adminPortal_Dialog.setObjectName("adminPortal_Dialog")
        adminPortal_Dialog.resize(671, 460)
        self.customerServices = QtWidgets.QWidget(adminPortal_Dialog)
        self.customerServices.setGeometry(QtCore.QRect(10, 10, 651, 441))
        self.customerServices.setStyleSheet("border: 8px solid black;\n"
    "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255), "
     "stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n""")
        self.customerServices.setObjectName("customerServices")
        self.tServices_txt = QtWidgets.QLabel(self.customerServices)
        self.tServices_txt.setGeometry(QtCore.QRect(150, 10, 391, 51))
        self.tServices_txt.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 24px;\n"
    "border: none;\n"
    "background-color: none;\n"
    "color: yellow;\n""")
        self.tServices_txt.setObjectName("tServices_txt")
        self.logoutBtn = QtWidgets.QPushButton(self.customerServices,
                                                       clicked=lambda: self.logout_clicked())
        self.logoutBtn.setGeometry(QtCore.QRect(520, 390, 111, 31))
        self.logoutBtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "color: white;")
        self.logoutBtn.setObjectName("logoutBtn")
        self.confirmBookingBtn = QtWidgets.QPushButton(self.customerServices,
                                                       clicked=lambda: self.confirmBooking_clicked())
        self.confirmBookingBtn.setGeometry(QtCore.QRect(30, 220, 141, 131))
        self.confirmBookingBtn.setStyleSheet("background: blue;\n"
    "border: 3px solid rgb(255, 0, 127);\n"
    "box-sizing: border-box;\n"
    "border-radius: 10px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 13px;\n"
    "text-align: center;\n"
    "color: white;\n"
    "padding-top: 100px;")
        self.confirmBookingBtn.setObjectName("confirmBookingBtn")
        self.adminServices = QtWidgets.QLabel(self.customerServices)
        self.adminServices.setGeometry(QtCore.QRect(0, 0, 651, 71))
        self.adminServices.setStyleSheet("background-color: black;\n"
    "border-bottom: 2px solid black;")
        self.adminServices.setText("")
        self.adminServices.setObjectName("adminServices")
        self.adminRegisterBtn = QtWidgets.QPushButton(self.customerServices,
                                                       clicked=lambda: self.adminRegister_clicked())
        self.adminRegisterBtn.setGeometry(QtCore.QRect(330, 220, 141, 131))
        self.adminRegisterBtn.setStyleSheet("background: blue;\n"
    "border: 3px solid red;\n"
    "box-sizing: border-box;\n"
    "border-radius: 10px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 11.5px;\n"
    "text-align: center;\n"
    "color: white;\n"
    "padding-top: 100px;")
        self.adminRegisterBtn.setObjectName("adminRegisterBtn")
        self.driverRegisterBtn = QtWidgets.QPushButton(self.customerServices,
                                                       clicked=lambda: self.driverRegister_clicked())
        self.driverRegisterBtn.setGeometry(QtCore.QRect(480, 220, 141, 131))
        self.driverRegisterBtn.setStyleSheet("background: blue;\n"
    "border: 3px solid red;\n"
    "box-sizing: border-box;\n"
    "border-radius: 10px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 11.5px;\n"
    "text-align: center;\n"
    "color: white;\n"
    "padding-top: 100px;")
        self.driverRegisterBtn.setObjectName("driverRegisterBtn")
        self.adminForgotPasswordbtn = QtWidgets.QPushButton(self.customerServices,
                                                      clicked=lambda: self.adminForgotPassword_clicked())
        self.adminForgotPasswordbtn.setGeometry(QtCore.QRect(20, 390, 171, 31))
        self.adminForgotPasswordbtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "color: white;")
        self.adminForgotPasswordbtn.setObjectName("adminForgotPasswordbtn")
        self.driverForgotPasswordbtn = QtWidgets.QPushButton(self.customerServices,
                                                             clicked=lambda: self.driverForgotPassword_button_click())
        self.driverForgotPasswordbtn.setGeometry(QtCore.QRect(210, 390, 171, 31))
        self.driverForgotPasswordbtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "color: white;")
        self.driverForgotPasswordbtn.setObjectName("driverForgotPasswordbtn")
        self.assignDriverIcon = QtWidgets.QLabel(self.customerServices)
        self.assignDriverIcon.setGeometry(QtCore.QRect(200, 230, 101, 81))
        self.assignDriverIcon.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.assignDriverIcon.setText("")
        self.assignDriverIcon.setPixmap(QtGui.QPixmap("../Sketch imgs/assignDriver.png"))
        self.assignDriverIcon.setScaledContents(True)
        self.assignDriverIcon.setObjectName("assignDriverIcon")
        self.confirmBookingIcon = QtWidgets.QLabel(self.customerServices)
        self.confirmBookingIcon.setGeometry(QtCore.QRect(50, 230, 101, 91))
        self.confirmBookingIcon.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.confirmBookingIcon.setText("")
        self.confirmBookingIcon.setPixmap(QtGui.QPixmap("../Sketch imgs/create.png"))
        self.confirmBookingIcon.setScaledContents(True)
        self.confirmBookingIcon.setObjectName("confirmBookingIcon")
        self.assignDriverBtn = QtWidgets.QPushButton(self.customerServices,
                                                       clicked=lambda: self.assignDriver_clicked())
        self.assignDriverBtn.setGeometry(QtCore.QRect(180, 220, 141, 131))
        self.assignDriverBtn.setStyleSheet("background: blue;\n"
    "border: 3px solid rgb(255, 0, 127);\n"
    "box-sizing: border-box;\n"
    "border-radius: 10px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 12px;\n"
    "text-align: center;\n"
    "color: white;\n"
    "padding-top: 100px;")
        self.assignDriverBtn.setObjectName("assignDriverBtn")
        self.aRegisterIcon = QtWidgets.QLabel(self.customerServices)
        self.aRegisterIcon.setGeometry(QtCore.QRect(360, 230, 91, 71))
        self.aRegisterIcon.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.aRegisterIcon.setText("")
        self.aRegisterIcon.setPixmap(QtGui.QPixmap("../Sketch imgs/adminRegister.png"))
        self.aRegisterIcon.setScaledContents(True)
        self.aRegisterIcon.setObjectName("aRegisterIcon")
        self.dRegisterIcon = QtWidgets.QLabel(self.customerServices)
        self.dRegisterIcon.setGeometry(QtCore.QRect(500, 230, 111, 81))
        self.dRegisterIcon.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.dRegisterIcon.setText("")
        self.dRegisterIcon.setPixmap(QtGui.QPixmap("../Sketch imgs/driverRegister.png"))
        self.dRegisterIcon.setScaledContents(True)
        self.dRegisterIcon.setObjectName("dRegisterIcon")
        self.welcome = QtWidgets.QLabel(self.customerServices)
        self.welcome.setGeometry(QtCore.QRect(230, 80, 201, 81))
        self.welcome.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.welcome.setText("")
        self.welcome.setPixmap(QtGui.QPixmap("../Sketch imgs/welcomeAdmin.png"))
        self.welcome.setScaledContents(True)
        self.welcome.setObjectName("welcome")
        self.logo = QtWidgets.QLabel(self.customerServices)
        self.logo.setGeometry(QtCore.QRect(40, 0, 71, 71))
        self.logo.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.logo.setStyleSheet("background-color: none;\n"
    "border: none;\n"
    "padding: 5px 3px;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.slogan = QtWidgets.QLabel(self.customerServices)
        self.slogan.setGeometry(QtCore.QRect(160, 160, 331, 41))
        self.slogan.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "color: white;\n"
    "background-color:none;")
        self.slogan.setObjectName("slogan")
        self.assignDriverBtn.raise_()
        self.adminServices.raise_()
        self.logoutBtn.raise_()
        self.confirmBookingBtn.raise_()
        self.tServices_txt.raise_()
        self.adminRegisterBtn.raise_()
        self.driverRegisterBtn.raise_()
        self.adminForgotPasswordbtn.raise_()
        self.driverForgotPasswordbtn.raise_()
        self.assignDriverIcon.raise_()
        self.confirmBookingIcon.raise_()
        self.aRegisterIcon.raise_()
        self.dRegisterIcon.raise_()
        self.welcome.raise_()
        self.logo.raise_()
        self.slogan.raise_()

        self.retranslateUi(adminPortal_Dialog)
        QtCore.QMetaObject.connectSlotsByName(adminPortal_Dialog)

    def retranslateUi(self, adminPortal_Dialog):
        _translate = QtCore.QCoreApplication.translate
        adminPortal_Dialog.setWindowTitle(_translate("adminPortal_Dialog", "Dialog"))
        self.tServices_txt.setText(_translate("adminPortal_Dialog", "TAXI COMPANY ADMIN PORTAL"))
        self.logoutBtn.setText(_translate("adminPortal_Dialog", "LOGOUT"))
        self.confirmBookingBtn.setText(_translate("adminPortal_Dialog", "CONFIRM BOOKINGS"))
        self.adminRegisterBtn.setText(_translate("adminPortal_Dialog", "ADMIN REGISTRATION"))
        self.driverRegisterBtn.setText(_translate("adminPortal_Dialog", "DRIVER REGISTRATION"))
        self.adminForgotPasswordbtn.setText(_translate("adminPortal_Dialog", "Reset Admin Password"))
        self.driverForgotPasswordbtn.setText(_translate("adminPortal_Dialog", "Reset Driver Password"))
        self.assignDriverBtn.setText(_translate("adminPortal_Dialog", "ASSIGN DRIVER"))
        self.slogan.setText(_translate("adminPortal_Dialog",
        "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Dear Admins, always remember "
        "together <br>we acheive more!!</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminPortal_Dialog = QtWidgets.QDialog()
    ui = Ui_adminPortal_Dialog()
    ui.adminPortal_setupUi(adminPortal_Dialog)
    adminPortal_Dialog.show()
    sys.exit(app.exec_())
