# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
import adminServices

#conn = sqlite3.connect(':memory:')  # testing in memory
conn = sqlite3.connect('taxi.db')  # creates the actual database
c = conn.cursor()   # The cursor to take data to and from the database.
c.execute("""CREATE TABLE if not exists Admin (
                   adminId INTEGER PRIMARY KEY AUTOINCREMENT,
                   first_name text,
                   last_name text,
                   email text,
                   password text,
                   address text,
                   telephone_no text
                   )""")   # creates the table associated with the text field aka line edits

c.execute("""INSERT OR IGNORE INTO Admin VALUES ('1', 'Ali', 'Kahn', 'khan@gmail.com', '123', 'Arima', '1-868-310-9969')""")
conn.commit()

class Ui_adminRegisterScreen_Dialog(object):

        def __init__(self, Dialog):  # creation of a constructor
                self.Dialog = QtWidgets.QDialog()  # this class has one attribute
                self.adminRegisterScreen_setupUi(self.Dialog)  # attribute is need to setup the ui

        def its_showtime(self):     # used to show the dialog
                self.Dialog.show()

        def its_closetime(self):   # used to close the dialog
                self.Dialog.close()

        def back_button_click(self):
                self.dialog = QtWidgets.QDialog()    # goes back to the Admin Services Screen
                aS = adminServices.Ui_adminPortal_Dialog(self.dialog)
                aS.its_showtime()
                self.its_closetime()

        def registerAsAdmin_button_click(self):
                self.insert_record()   # inserts the user data
                conn.commit()   # commits the data to the database
                conn.close()    # closes the database connection
                self.disable_fields_and_Buttons()   # function that disables fields and button.
                self.showdialog("Congratulations, you have successfully been registered!")

        def insert_record(self):
                with conn:
                        c.execute(
                                "INSERT INTO Admin VALUES (NULL, :first_name, :last_name, :email, :password, :address,"
                                " :telephone_no)",
                                {'adminId': self.aAdminIDLineEdit.text(),
                                 'first_name': self.aFirstNameLineEdit.text(), # disable the firstName field
                                 'last_name': self.aLastNameLineEdit.text(),  # disable the LastName field
                                 'email': self.aEmailLineEdit.text(),   # disable the email field
                                 'password': self.aPasswordLineEdit.text(),  # disable the password field
                                 'address': self.aAddressLineEdit.text(),   # disable the address field
                                 'telephone_no': self.aTelephoneNoLineEdit.text()})   # disable the telephoneNo field

        def disable_fields_and_Buttons(self):
                self.aFirstNameLineEdit.setEnabled(False)  # disable the firstName field
                self.aLastNameLineEdit.setEnabled(False)   # disable the LastName field
                self.aEmailLineEdit.setEnabled(False)      # disable the email field
                self.aPasswordLineEdit.setEnabled(False)   # disable the password field
                self.aAddressLineEdit.setEnabled(False)    # disable the address field
                self.aTelephoneNoLineEdit.setEnabled(False)  # disable the telephoneNo field
                self.registerAsAdminBtn.setEnabled(False)  # disable the registerAsAdminBtn

        def showdialog(self, message):
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("This is a confirmation message.")
                msg.setInformativeText(message)
                msg.setWindowTitle("Confirmation")
                msg.setDetailedText("The details are as follows:" + message)
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                retval = msg.exec_()

        def adminRegisterScreen_setupUi(self, adminRegisterScreen_Dialog):
                adminRegisterScreen_Dialog.setObjectName("adminRegisterScreen_Dialog")
                adminRegisterScreen_Dialog.resize(671, 460)
                self.adminRegisterScreen = QtWidgets.QWidget(adminRegisterScreen_Dialog)
                self.adminRegisterScreen.setGeometry(QtCore.QRect(10, 10, 651, 441))
                self.adminRegisterScreen.setStyleSheet("border: 8px solid black;\n"
        "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255), "
        "stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n""")
                self.adminRegisterScreen.setObjectName("adminRegisterScreen")
                self.register_txt = QtWidgets.QLabel(self.adminRegisterScreen)
                self.register_txt.setGeometry(QtCore.QRect(200, 20, 291, 21))
                self.register_txt.setStyleSheet("font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 24px;\n"
        "border: none;\n"
        "background-color: none;\n"
        "color: yellow;\n"
        "")
                self.register_txt.setObjectName("register_txt")
                self.backBtn = QtWidgets.QPushButton(self.adminRegisterScreen,
                                                           clicked=lambda: self.back_button_click())
                self.backBtn.setGeometry(QtCore.QRect(530, 390, 91, 31))
                self.backBtn.setStyleSheet("background: red;\n"
        "border: 3px solid blue;\n"
        "box-sizing: border-box;\n"
        "border-radius: 15px;\n"
        "font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: white;")
                self.backBtn.setObjectName("backBtn")
                self.registerAsAdminBtn = QtWidgets.QPushButton(self.adminRegisterScreen,
                                                           clicked=lambda: self.registerAsAdmin_button_click())
                self.registerAsAdminBtn.setGeometry(QtCore.QRect(250, 290, 161, 31))
                self.registerAsAdminBtn.setStyleSheet("background: blue;\n"
        "border: 2px solid rgb(255, 0, 127);\n"
        "box-sizing: border-box;\n"
        "border-radius: 10px;\n"
        "font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: white;")
                self.registerAsAdminBtn.setObjectName("registerAsAdminBtn")
                self.label = QtWidgets.QLabel(self.adminRegisterScreen)
                self.label.setGeometry(QtCore.QRect(0, 0, 651, 61))
                self.label.setStyleSheet("background-color: black;\n"
        "border-bottom: 2px solid black;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.firstNameLabel = QtWidgets.QLabel(self.adminRegisterScreen)
                self.firstNameLabel.setGeometry(QtCore.QRect(50, 190, 91, 21))
                self.firstNameLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.firstNameLabel.setObjectName("firstNameLabel")
                self.emailLabel = QtWidgets.QLabel(self.adminRegisterScreen)
                self.emailLabel.setGeometry(QtCore.QRect(50, 250, 91, 21))
                self.emailLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.emailLabel.setObjectName("emailLabel")
                self.addressLabel = QtWidgets.QLabel(self.adminRegisterScreen)
                self.addressLabel.setGeometry(QtCore.QRect(330, 220, 91, 21))
                self.addressLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.addressLabel.setObjectName("addressLabel")
                self.telephoneNoLabel = QtWidgets.QLabel(self.adminRegisterScreen)
                self.telephoneNoLabel.setGeometry(QtCore.QRect(330, 160, 101, 21))
                self.telephoneNoLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.telephoneNoLabel.setObjectName("telephoneNoLabel")
                self.LastNameLabel = QtWidgets.QLabel(self.adminRegisterScreen)
                self.LastNameLabel.setGeometry(QtCore.QRect(50, 220, 91, 21))
                self.LastNameLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.LastNameLabel.setObjectName("LastNameLabel")
                self.passwordLabel = QtWidgets.QLabel(self.adminRegisterScreen)
                self.passwordLabel.setGeometry(QtCore.QRect(330, 190, 91, 21))
                self.passwordLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.passwordLabel.setObjectName("passwordLabel")
                self.aTelephoneNoLineEdit = QtWidgets.QLineEdit(self.adminRegisterScreen)
                self.aTelephoneNoLineEdit.setGeometry(QtCore.QRect(440, 160, 161, 20))
                self.aTelephoneNoLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.aTelephoneNoLineEdit.setObjectName("aTelephoneNoLineEdit")
                self.aAddressLineEdit = QtWidgets.QLineEdit(self.adminRegisterScreen)
                self.aAddressLineEdit.setGeometry(QtCore.QRect(440, 220, 161, 20))
                self.aAddressLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.aAddressLineEdit.setObjectName("aAddressLineEdit")
                self.aPasswordLineEdit = QtWidgets.QLineEdit(self.adminRegisterScreen)
                self.aPasswordLineEdit.setGeometry(QtCore.QRect(440, 190, 161, 20))
                self.aPasswordLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.aPasswordLineEdit.setObjectName("aPasswordLineEdit")
                self.aEmailLineEdit = QtWidgets.QLineEdit(self.adminRegisterScreen)
                self.aEmailLineEdit.setGeometry(QtCore.QRect(140, 250, 161, 20))
                self.aEmailLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.aEmailLineEdit.setObjectName("aEmailLineEdit")
                self.aLastNameLineEdit = QtWidgets.QLineEdit(self.adminRegisterScreen)
                self.aLastNameLineEdit.setGeometry(QtCore.QRect(140, 220, 161, 20))
                self.aLastNameLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.aLastNameLineEdit.setObjectName("aLastNameLineEdit")
                self.aFirstNameLineEdit = QtWidgets.QLineEdit(self.adminRegisterScreen)
                self.aFirstNameLineEdit.setGeometry(QtCore.QRect(140, 190, 161, 20))
                self.aFirstNameLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.aFirstNameLineEdit.setText("")
                self.aFirstNameLineEdit.setObjectName("aFirstNameLineEdit")
                self.label_11 = QtWidgets.QLabel(self.adminRegisterScreen)
                self.label_11.setGeometry(QtCore.QRect(30, 140, 591, 201))
                self.label_11.setStyleSheet("border: 2px solid rgb(255, 0, 127);\n"
        "background-color: rgb(149, 200, 255);")
                self.label_11.setText("")
                self.label_11.setObjectName("label_11")
                self.registerSlogan = QtWidgets.QLabel(self.adminRegisterScreen)
                self.registerSlogan.setGeometry(QtCore.QRect(120, 90, 401, 16))
                self.registerSlogan.setStyleSheet("font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 15px;\n"
        "text-align: center;\n"
        "border: none;\n"
        "color: white;\n"
        "background-color: none;\n""")
                self.registerSlogan.setObjectName("registerSlogan")
                self.aAdminIDLineEdit = QtWidgets.QLineEdit(self.adminRegisterScreen)
                self.aAdminIDLineEdit.setGeometry(QtCore.QRect(140, 160, 161, 20))
                self.aAdminIDLineEdit.setStyleSheet("background: red;\n"
        "border: 1px solid blue;")
                self.aAdminIDLineEdit.setText("")
                self.aAdminIDLineEdit.setEnabled(False)
                self.aAdminIDLineEdit.setObjectName("aAdminIDLineEdit")
                self.customerIDLabel = QtWidgets.QLabel(self.adminRegisterScreen)
                self.customerIDLabel.setGeometry(QtCore.QRect(50, 160, 91, 21))
                self.customerIDLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: red;\n"
        "border: none;\n"
        "background-color: none;")
                self.customerIDLabel.setObjectName("customerIDLabel")
                self.logo = QtWidgets.QLabel(self.adminRegisterScreen)
                self.logo.setGeometry(QtCore.QRect(50, 0, 61, 61))
                self.logo.setStyleSheet("background-color: none;\n"
        "border: none;\n"
        "padding: 3px 0px;")
                self.logo.setText("")
                self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
                self.logo.setScaledContents(True)
                self.logo.setObjectName("logo")
                self.logo_2 = QtWidgets.QLabel(self.adminRegisterScreen)
                self.logo_2.setGeometry(QtCore.QRect(30, 360, 101, 61))
                self.logo_2.setStyleSheet("background-color: none;\n"
        "border: none;")
                self.logo_2.setText("")
                self.logo_2.setPixmap(QtGui.QPixmap("../Sketch imgs/registerNow.png"))
                self.logo_2.setScaledContents(True)
                self.logo_2.setObjectName("logo_2")
                self.label_3 = QtWidgets.QLabel(self.adminRegisterScreen)
                self.label_3.setGeometry(QtCore.QRect(170, 160, 91, 20))
                self.label_3.setStyleSheet("background-color: none;\n"
        "border: none;")
                self.label_3.setObjectName("label_3")
                self.label.raise_()
                self.label_11.raise_()
                self.backBtn.raise_()
                self.registerAsAdminBtn.raise_()
                self.register_txt.raise_()
                self.firstNameLabel.raise_()
                self.emailLabel.raise_()
                self.addressLabel.raise_()
                self.telephoneNoLabel.raise_()
                self.LastNameLabel.raise_()
                self.passwordLabel.raise_()
                self.aTelephoneNoLineEdit.raise_()
                self.aAddressLineEdit.raise_()
                self.aPasswordLineEdit.raise_()
                self.aEmailLineEdit.raise_()
                self.aLastNameLineEdit.raise_()
                self.aFirstNameLineEdit.raise_()
                self.registerSlogan.raise_()
                self.aAdminIDLineEdit.raise_()
                self.customerIDLabel.raise_()
                self.logo.raise_()
                self.logo_2.raise_()
                self.label_3.raise_()

                self.retranslateUi(adminRegisterScreen_Dialog)
                QtCore.QMetaObject.connectSlotsByName(adminRegisterScreen_Dialog)

        def retranslateUi(self, adminRegisterScreen_Dialog):
                _translate = QtCore.QCoreApplication.translate
                adminRegisterScreen_Dialog.setWindowTitle(_translate("adminRegisterScreen_Dialog", "Dialog"))
                self.register_txt.setText(_translate("adminRegisterScreen_Dialog", "ADMIN REGISTRATION"))
                self.backBtn.setText(_translate("adminRegisterScreen_Dialog", "BACK"))
                self.registerAsAdminBtn.setText(_translate("adminRegisterScreen_Dialog", "Register as Admin"))
                self.firstNameLabel.setText(_translate("adminRegisterScreen_Dialog", "First Name"))
                self.emailLabel.setText(_translate("adminRegisterScreen_Dialog", "Email"))
                self.addressLabel.setText(_translate("adminRegisterScreen_Dialog", "Address"))
                self.telephoneNoLabel.setText(_translate("adminRegisterScreen_Dialog", "Telephone No"))
                self.LastNameLabel.setText(_translate("adminRegisterScreen_Dialog", "Last Name"))
                self.passwordLabel.setText(_translate("adminRegisterScreen_Dialog", "Password"))
                self.registerSlogan.setText(_translate("adminRegisterScreen_Dialog",
                "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">REGISTER NOW &amp; BE "
                "PART OF THE TAXI COMPANY!!</span></p></body></html>"))
                self.customerIDLabel.setText(_translate("adminRegisterScreen_Dialog", "Admin ID"))
                self.label_3.setText(_translate("adminRegisterScreen_Dialog", "Auto Generated"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminRegisterScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_adminRegisterScreen_Dialog()
    ui.adminRegisterScreen_setupUi(adminRegisterScreen_Dialog)
    adminRegisterScreen_Dialog.show()
    sys.exit(app.exec_())
