# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import homePage


class Ui_calendarScreen_Dialog(object):
    def __init__(self, Dialog):
        self.Dialog = QtWidgets.QDialog()
        self.calendarScreen_setupUi(self.Dialog)

    def its_showtime(self):
        self.Dialog.show()

    def its_closetime(self):
        self.Dialog.close()

    def calendarBack_clicked(self):
        self.dialog = QtWidgets.QDialog()
        hP = homePage.Ui_homeScreen_Dialog(self.dialog)
        hP.its_showtime()
        self.its_closetime()

    def calendarScreen_setupUi(self, calendarScreen_Dialog):
        calendarScreen_Dialog.setObjectName("calendarScreen_Dialog")
        calendarScreen_Dialog.resize(671, 460)
        self.calendarScreen = QtWidgets.QWidget(calendarScreen_Dialog)
        self.calendarScreen.setGeometry(QtCore.QRect(10, 10, 651, 441))
        self.calendarScreen.setStyleSheet("border: 8px solid black;\n"
    "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255), "
     "stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n""")
        self.calendarScreen.setObjectName("calendarScreen")
        self.calendar_txt = QtWidgets.QLabel(self.calendarScreen)
        self.calendar_txt.setGeometry(QtCore.QRect(260, 10, 161, 51))
        self.calendar_txt.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 28px;\n"
    "border: none;\n"
    "background-color: none;\n"
    "color: yellow;")
        self.calendar_txt.setObjectName("calendar_txt")
        self.calendarLabel = QtWidgets.QLabel(self.calendarScreen)
        self.calendarLabel.setGeometry(QtCore.QRect(120, 90, 411, 41))
        self.calendarLabel.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 15px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "color:white;\n"
    "background-color: none;")
        self.calendarLabel.setObjectName("calendarLabel")
        self.calendarBackBtn = QtWidgets.QPushButton(self.calendarScreen,
                                                      clicked=lambda: self.calendarBack_clicked())
        self.calendarBackBtn.setGeometry(QtCore.QRect(290, 390, 91, 31))
        self.calendarBackBtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 13px;\n"
    "text-align: center;\n"
    "color: white;")
        self.calendarBackBtn.setObjectName("calendarBackBtn")
        self.label = QtWidgets.QLabel(self.calendarScreen)
        self.label.setGeometry(QtCore.QRect(0, 0, 651, 71))
        self.label.setStyleSheet("background-color:balck;\n""")
        self.label.setText("")
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.calendarScreen)
        self.calendarWidget.setGeometry(QtCore.QRect(100, 140, 441, 231))
        self.calendarWidget.setStyleSheet("background-color: rgb(155, 170, 168);\n"
    "color: black;\n"
    "border: 2px solid rgb(255, 0, 127);\n"
    "font-size: 14px;\n"
    "padding: 5px 15px;\n""\n""\n""\n""")
        self.calendarWidget.setObjectName("calendarWidget")
        self.logo = QtWidgets.QLabel(self.calendarScreen)
        self.logo.setGeometry(QtCore.QRect(40, 0, 71, 71))
        self.logo.setStyleSheet("background-color: none;\n"
    "border: none;\n"
    "padding: 5px 3px;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label.raise_()
        self.calendar_txt.raise_()
        self.calendarLabel.raise_()
        self.calendarBackBtn.raise_()
        self.calendarWidget.raise_()
        self.logo.raise_()

        self.retranslateUi(calendarScreen_Dialog)
        QtCore.QMetaObject.connectSlotsByName(calendarScreen_Dialog)

    def retranslateUi(self, calendarScreen_Dialog):
        _translate = QtCore.QCoreApplication.translate
        calendarScreen_Dialog.setWindowTitle(_translate("calendarScreen_Dialog", "Dialog"))
        self.calendar_txt.setText(_translate("calendarScreen_Dialog", "CALENDAR"))
        self.calendarLabel.setText(_translate("calendarScreen_Dialog",
        "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Can\'t remember what day you "
        "need to Book a Trip for?< br> Check out the Calendar to make sure!</span></p></body></html>"))
        self.calendarBackBtn.setText(_translate("calendarScreen_Dialog", "BACK"))
        self.calendarWidget.setToolTip(_translate("calendarScreen_Dialog",
        "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calendarScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_calendarScreen_Dialog()
    ui.calendarScreen_setupUi(calendarScreen_Dialog)
    calendarScreen_Dialog.show()
    sys.exit(app.exec_())
