# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cancelABooking.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import customerServices

conn = sqlite3.connect('taxi.db')   # creates the actual database
c = conn.cursor()      # The cursor to take data to and from the database.


class Ui_cancelBookingScreen_Dialog(object):
    def __init__(self, Dialog):    # creation of a constructor
        self.Dialog = QtWidgets.QDialog()     # this class has one attribute
        self.cancelBookingScreen_setupUi(self.Dialog)   # attribute is need to setup the ui

    def its_showtime(self):    # used to show the dialog
        self.Dialog.show()

    def its_closetime(self):   # used to close the dialog
        self.Dialog.close()

    def back_button_click(self):   # goes back to the Customer Services Screen.
        self.dialog = QtWidgets.QDialog()
        cS = customerServices.Ui_CustomerPortal(self.dialog)
        cS.its_showtime()
        self.its_closetime()

    def confirmCancelBooking_button_click(self):   # Button to cancel a booking.
        if self.BookingIDTxt.text() and \
           self.BookingIDTxt.text() in self.get_bookingID_Verification().__str__():
         self.remove_record()    # removes the customer booking
         self.disable_fields_and_Buttons()    # function that disables fields and button.
         self.showdialog("Congratulations, your booking was successfully removed!")
        else:
            self.wrongBookingID("Sorry, your BookingID is not Valid.")

    def remove_record(self):    # Delete Statement
        with conn:
            c.execute("DELETE from Booking Where bookingId = :bookingId",
                      {'bookingId': self.BookingIDTxt.text()})

    def get_bookingID_Verification(self):     # gets booking Id from the Booking table.
        c.execute("SELECT * FROM Booking WHERE bookingId=:bookingId",
                  {'bookingId': self.BookingIDTxt.text()})
        return c.fetchall()  # returns the record from the database

    def disable_fields_and_Buttons(self):
        self.BookingIDTxt.setEnabled(False)      # disable the Booking Id field.
        self.confirmCancelBookingBtn.setEnabled(False)     # disable the confirmCancelBooking button.

    def showdialog(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("This is a confirmation message.")
        msg.setInformativeText(message)
        msg.setWindowTitle("Confirmation")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def wrongBookingID(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Invalid BookingID.")
        msg.setInformativeText(message)
        msg.setWindowTitle("Notification")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def cancelBookingScreen_setupUi(self, cancelBookingScreen_Dialog):
        cancelBookingScreen_Dialog.setObjectName("cancelBookingScreen_Dialog")
        cancelBookingScreen_Dialog.resize(671, 460)
        self.cancelABookingScreen = QtWidgets.QWidget(cancelBookingScreen_Dialog)
        self.cancelABookingScreen.setGeometry(QtCore.QRect(10, 10, 651, 441))
        self.cancelABookingScreen.setStyleSheet("border: 8px solid black;\n"
    "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255),"
    " stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n" "")
        self.cancelABookingScreen.setObjectName("cancelABookingScreen")
        self.cancel_txt = QtWidgets.QLabel(self.cancelABookingScreen)
        self.cancel_txt.setGeometry(QtCore.QRect(230, 20, 221, 31))
        self.cancel_txt.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 24px;\n"
    "border: none;\n"
    "background-color: none;\n"
    "color: yellow;\n""")
        self.cancel_txt.setObjectName("cancel_txt")
        self.backBtn = QtWidgets.QPushButton(self.cancelABookingScreen,
                                                             clicked=lambda: self.back_button_click())
        self.backBtn.setGeometry(QtCore.QRect(530, 390, 91, 31))
        self.backBtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 13px;\n"
    "text-align: center;\n"
    "color: white;")
        self.backBtn.setObjectName("backBtn")
        self.label = QtWidgets.QLabel(self.cancelABookingScreen)
        self.label.setGeometry(QtCore.QRect(0, 0, 651, 71))
        self.label.setStyleSheet("background-color: black;\n"
    "border-bottom: 2px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.BookingIDLabel = QtWidgets.QLabel(self.cancelABookingScreen)
        self.BookingIDLabel.setGeometry(QtCore.QRect(180, 240, 91, 21))
        self.BookingIDLabel.setStyleSheet("font-family: Roboto;\n"
    "font-style:normal;\n"
    "font-weight:500;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "color: #000000;\n"
    "border: none;\n"
    "background-color: none;")
        self.BookingIDLabel.setObjectName("BookingIDLabel")
        self.BookingIDTxt = QtWidgets.QLineEdit(self.cancelABookingScreen)
        self.BookingIDTxt.setGeometry(QtCore.QRect(280, 240, 211, 20))
        self.BookingIDTxt.setStyleSheet("background: #C4C4C4;\n"
    "border: 1px solid blue;")
        self.BookingIDTxt.setObjectName("BookingIDTxt")
        self.label_11 = QtWidgets.QLabel(self.cancelABookingScreen)
        self.label_11.setGeometry(QtCore.QRect(50, 160, 551, 181))
        self.label_11.setStyleSheet("border: 2px solid rgb(255, 0, 127);\n"
    "background-color: rgb(149, 200, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.cancelSlogan = QtWidgets.QLabel(self.cancelABookingScreen)
        self.cancelSlogan.setGeometry(QtCore.QRect(100, 90, 461, 41))
        self.cancelSlogan.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 15px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "color:white;\n"
    "background-color: none;\n""")
        self.cancelSlogan.setObjectName("cancelSlogan")
        self.confirmCancelBookingBtn = QtWidgets.QPushButton(self.cancelABookingScreen,
                                                             clicked=lambda: self.confirmCancelBooking_button_click())
        self.confirmCancelBookingBtn.setGeometry(QtCore.QRect(270, 290, 151, 31))
        self.confirmCancelBookingBtn.setStyleSheet("background: blue;\n"
    "border: 2px solid rgb(255, 0, 127);\n"
    "box-sizing: border-box;\n"
    "border-radius: 10px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight:500;\n"
    "font-size: 13px;\n"
    "text-align: center;\n"
    "color: white;")
        self.confirmCancelBookingBtn.setObjectName("confirmCancelBookingBtn")
        self.logo = QtWidgets.QLabel(self.cancelABookingScreen)
        self.logo.setGeometry(QtCore.QRect(40, 0, 71, 71))
        self.logo.setStyleSheet("background-color: none;\n"
    "border: none;\n"
    "padding: 5px 3px;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logo_2 = QtWidgets.QLabel(self.cancelABookingScreen)
        self.logo_2.setGeometry(QtCore.QRect(20, 350, 101, 71))
        self.logo_2.setStyleSheet("background-color: none;\n""border: none;")
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("../Sketch imgs/cancel.png"))
        self.logo_2.setScaledContents(True)
        self.logo_2.setObjectName("logo_2")
        self.cancelInstruction = QtWidgets.QLabel(self.cancelABookingScreen)
        self.cancelInstruction.setGeometry(QtCore.QRect(130, 170, 391, 41))
        self.cancelInstruction.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 15px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "color:black;\n"
    "background-color: none;\n""")
        self.cancelInstruction.setObjectName("cancelInstruction")
        self.label_11.raise_()
        self.label.raise_()
        self.backBtn.raise_()
        self.cancel_txt.raise_()
        self.BookingIDLabel.raise_()
        self.BookingIDTxt.raise_()
        self.cancelSlogan.raise_()
        self.confirmCancelBookingBtn.raise_()
        self.logo.raise_()
        self.logo_2.raise_()
        self.cancelInstruction.raise_()

        self.retranslateUi(cancelBookingScreen_Dialog)
        QtCore.QMetaObject.connectSlotsByName(cancelBookingScreen_Dialog)

    def retranslateUi(self, cancelBookingScreen_Dialog):
        _translate = QtCore.QCoreApplication.translate
        cancelBookingScreen_Dialog.setWindowTitle(_translate("cancelBookingScreen_Dialog", "Dialog"))
        self.cancel_txt.setText(_translate("cancelBookingScreen_Dialog", "CANCEL BOOKING"))
        self.backBtn.setText(_translate("cancelBookingScreen_Dialog", "BACK"))
        self.BookingIDLabel.setText(_translate("cancelBookingScreen_Dialog", "Booking ID"))
        self.cancelSlogan.setText(_translate("cancelBookingScreen_Dialog",
        "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Please make sure you really want"
        " to cancel your booking <br/>before doing it!</span></p></body></html>"))
        self.confirmCancelBookingBtn.setText(_translate("cancelBookingScreen_Dialog", "CANCEL BOOKING"))
        self.cancelInstruction.setText(_translate("cancelBookingScreen_Dialog",
        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">To Cancel your booking, enter your "
        "Booking ID then click the <br>Cancel Booking button.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cancelBookingScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_cancelBookingScreen_Dialog()
    ui.cancelBookingScreen_setupUi(cancelBookingScreen_Dialog)
    cancelBookingScreen_Dialog.show()
    sys.exit(app.exec_())
