# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'driverLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import driverServices
from PyQt5.QtWidgets import QMessageBox
import homePage

conn = sqlite3.connect('taxi.db')  # creates the actual database
c = conn.cursor()    # The cursor to take data to and from the database.

class Ui_driverLoginScreen_Dialog(object):

    def __init__(self, Dialog):   # creation of a constructor
        self.Dialog = QtWidgets.QDialog()   # this class has one attribute
        self.driverLoginScreen_setupUi(self.Dialog)    # attribute is need to setup the ui

    def its_showtime(self):    # used to show the dialog
        self.Dialog.show()

    def its_closetime(self):   # used to close the dialog
        self.Dialog.close()

    def driverBack_clicked(self):
        self.dialog = QtWidgets.QDialog()     # goes back to the Home Page
        hP = homePage.Ui_homeScreen_Dialog(self.dialog)
        hP.its_showtime()
        self.its_closetime()

    def driverLogin_clicked(self):
        if self.driverPassword_txt.text() and self.driverEmail_txt.text() == \
           self.driverEmail_txt.text() in self.get_driver_info().__str__() and \
           self.driverPassword_txt.text() in self.get_driver_info().__str__():
            self.successfull_login_msg("Congratulations, your login credentials is correct. Enjoy!!")
            self.dialog = QtWidgets.QDialog()  # open the driver Services screen for positive login.
            dS = driverServices.Ui_driverScreen_Dialog(self.dialog)
            dS.its_showtime()
            self.its_closetime()
        else:
            self.failed_login_message("Incorrect Login Credentials!")

    def get_driver_info(self):
        c.execute("SELECT * FROM Driver WHERE email=:email",
                  {'email': self.driverEmail_txt.text()})
        return c.fetchall()    # returns the password from the database

    def successfull_login_msg(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Notification.")
        msg.setInformativeText(message)
        msg.setWindowTitle("Congratulations")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def failed_login_message(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Notification.")
        msg.setInformativeText(message)
        msg.setWindowTitle("Notification")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def driverLoginScreen_setupUi(self, driverLoginScreen_Dialog):
        driverLoginScreen_Dialog.setObjectName("driverLoginScreen_Dialog")
        driverLoginScreen_Dialog.resize(671, 460)
        self.driverLoginScreen = QtWidgets.QWidget(driverLoginScreen_Dialog)
        self.driverLoginScreen.setGeometry(QtCore.QRect(10, 10, 651, 441))
        self.driverLoginScreen.setStyleSheet("border: 8px solid black;\n"
    "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255), "
    "stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n""")
        self.driverLoginScreen.setObjectName("driverLoginScreen")
        self.driverLoginBtn = QtWidgets.QPushButton(self.driverLoginScreen,
                                                    clicked=lambda: self.driverLogin_clicked())
        self.driverLoginBtn.setGeometry(QtCore.QRect(300, 300, 101, 31))
        self.driverLoginBtn.setStyleSheet("background-color: rgb(255, 0, 127);\n"
    "border: 3px solid #0029FF;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 12px;\n"
    "text-align: center;\n"
    "color: white;")
        self.driverLoginBtn.setObjectName("driverLoginBtn")
        self.driverEmail_txt = QtWidgets.QLineEdit(self.driverLoginScreen)
        self.driverEmail_txt.setGeometry(QtCore.QRect(250, 240, 231, 20))
        self.driverEmail_txt.setStyleSheet("background: #C4C4C4;\n"
    "border: 2px solid blue;")
        self.driverEmail_txt.setObjectName("driverEmail_txt")
        self.driverPassword_txt = QtWidgets.QLineEdit(self.driverLoginScreen)
        self.driverPassword_txt.setGeometry(QtCore.QRect(250, 270, 231, 20))
        self.driverPassword_txt.setStyleSheet("background: #C4C4C4;\n"
    "border: 2px solid blue;")
        self.driverPassword_txt.setObjectName("driverPassword_txt")
        self.driverPassword_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email_label = QtWidgets.QLabel(self.driverLoginScreen)
        self.email_label.setGeometry(QtCore.QRect(160, 240, 51, 16))
        self.email_label.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 15px;\n"
    "text-align: center;\n"
    "color: #000000;\n"
    "border: none;\n"
    "background-color: none;")
        self.email_label.setObjectName("email_label")
        self.password_label = QtWidgets.QLabel(self.driverLoginScreen)
        self.password_label.setGeometry(QtCore.QRect(160, 270, 81, 16))
        self.password_label.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 15px;\n"
    "text-align: center;\n"
    "color: #000000;\n"
    "border: none;\n"
    "background-color: none;")
        self.password_label.setObjectName("password_label")
        self.driverLoginLabel = QtWidgets.QLabel(self.driverLoginScreen)
        self.driverLoginLabel.setGeometry(QtCore.QRect(250, 180, 151, 41))
        self.driverLoginLabel.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 18px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "background-color: none;")
        self.driverLoginLabel.setObjectName("driverLoginLabel")
        self.driverBackBtn = QtWidgets.QPushButton(self.driverLoginScreen,
                                                    clicked=lambda: self.driverBack_clicked())
        self.driverBackBtn.setGeometry(QtCore.QRect(540, 390, 91, 31))
        self.driverBackBtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 13px;\n"
    "text-align: center;\n"
    "color: white;")
        self.driverBackBtn.setObjectName("driverBackBtn")
        self.border = QtWidgets.QLabel(self.driverLoginScreen)
        self.border.setGeometry(QtCore.QRect(50, 170, 551, 201))
        self.border.setStyleSheet("border: 3.5px dotted red;\n"
    "background-color:none;\n""\n""")
        self.border.setText("")
        self.border.setObjectName("border")
        self.logo = QtWidgets.QLabel(self.driverLoginScreen)
        self.logo.setGeometry(QtCore.QRect(270, 20, 111, 101))
        self.logo.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.slogan = QtWidgets.QLabel(self.driverLoginScreen)
        self.slogan.setGeometry(QtCore.QRect(110, 120, 441, 31))
        self.slogan.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "color: white;\n"
    "background-color:none;\n""")
        self.slogan.setObjectName("slogan")
        self.border.raise_()
        self.driverLoginBtn.raise_()
        self.driverEmail_txt.raise_()
        self.driverPassword_txt.raise_()
        self.email_label.raise_()
        self.password_label.raise_()
        self.driverLoginLabel.raise_()
        self.driverBackBtn.raise_()
        self.logo.raise_()
        self.slogan.raise_()

        self.retranslateUi(driverLoginScreen_Dialog)
        QtCore.QMetaObject.connectSlotsByName(driverLoginScreen_Dialog)

    def retranslateUi(self, driverLoginScreen_Dialog):
        _translate = QtCore.QCoreApplication.translate
        driverLoginScreen_Dialog.setWindowTitle(_translate("driverLoginScreen_Dialog", "Dialog"))
        self.driverLoginBtn.setText(_translate("driverLoginScreen_Dialog", "LOGIN"))
        self.email_label.setText(_translate("driverLoginScreen_Dialog", "Email"))
        self.password_label.setText(_translate("driverLoginScreen_Dialog", "Password"))
        self.driverLoginLabel.setText(_translate("driverLoginScreen_Dialog",
        "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">DRIVER LOGIN</span>"
        "</p></body></html>"))
        self.driverBackBtn.setText(_translate("driverLoginScreen_Dialog", "BACK"))
        self.slogan.setText(_translate("driverLoginScreen_Dialog",
        "<html><head/><body><p align=\"center\">Mind on the Drive, Hands on the Wheel and Eyes on the Road!"
        "</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    driverLoginScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_driverLoginScreen_Dialog()
    ui.driverLoginScreen_DsetupUi(driverLoginScreen_Dialog)
    driverLoginScreen_Dialog.show()
    sys.exit(app.exec_())
