# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'driverServices.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import driverViewBooking
import homePage


class Ui_driverScreen_Dialog(object):
    def __init__(self, Dialog):    # creation of a constructor
        self.Dialog = QtWidgets.QDialog()     # this class has one attribute
        self.driverScreen_setupUi(self.Dialog)    # attribute is need to setup the ui

    def its_showtime(self):    # used to show the dialog
        self.Dialog.show()

    def its_closetime(self):   # used to close the dialog
        self.Dialog.close()

    def logout_button_click(self):    # goes back to the Home Screen.
        self.dialog = QtWidgets.QDialog()
        hP = homePage.Ui_homeScreen_Dialog(self.dialog)
        hP.its_showtime()
        self.its_closetime()

    def dViewBooking_clicked(self):    # open the driver view screen
        self.dialog = QtWidgets.QDialog()
        dVB = driverViewBooking.Ui_driverViewBookingScreen_Dialog(self.dialog)
        dVB.its_showtime()
        self.its_closetime()

    def driverScreen_setupUi(self, driverScreen_Dialog):
        driverScreen_Dialog.setObjectName("driverScreen_Dialog")
        driverScreen_Dialog.resize(671, 460)
        self.driverPortal = QtWidgets.QWidget(driverScreen_Dialog)
        self.driverPortal.setGeometry(QtCore.QRect(10, 10, 651, 441))
        self.driverPortal.setStyleSheet("border: 8px solid black;\n"
    "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255), "
    "stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n""")
        self.driverPortal.setObjectName("driverPortal")
        self.dServices_txt = QtWidgets.QLabel(self.driverPortal)
        self.dServices_txt.setGeometry(QtCore.QRect(200, 20, 271, 31))
        self.dServices_txt.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 24px;\n"
    "border: none;\n"
    "background-color: none;\n"
    "color: yellow;\n""")
        self.dServices_txt.setObjectName("dServices_txt")
        self.logoutBtn = QtWidgets.QPushButton(self.driverPortal,
                                               clicked=lambda: self.logout_button_click())
        self.logoutBtn.setGeometry(QtCore.QRect(510, 390, 121, 31))
        self.logoutBtn.setStyleSheet("background: red;\n"
    "border: 3px solid blue;\n"
    "box-sizing: border-box;\n"
    "border-radius: 15px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "color: white;")
        self.logoutBtn.setObjectName("logoutBtn")
        self.dViewBookingBtn = QtWidgets.QPushButton(self.driverPortal,
                                                       clicked=lambda: self.dViewBooking_clicked())
        self.dViewBookingBtn.setGeometry(QtCore.QRect(240, 230, 151, 131))
        self.dViewBookingBtn.setStyleSheet("background: blue;\n"
    "border: 3px solid red;\n"
    "box-sizing: border-box;\n"
    "border-radius: 10px;\n"
    "font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 13px;\n"
    "text-align: center;\n"
    "color: white;\n"
    "padding-top: 100px;")
        self.dViewBookingBtn.setObjectName("dViewBookingBtn")
        self.label = QtWidgets.QLabel(self.driverPortal)
        self.label.setGeometry(QtCore.QRect(0, 0, 651, 71))
        self.label.setStyleSheet("background-color: black;\n"
    "border-bottom: 2px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.logo = QtWidgets.QLabel(self.driverPortal)
        self.logo.setGeometry(QtCore.QRect(40, 0, 71, 71))
        self.logo.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.logo.setStyleSheet("background-color: none;\n"
    "border: none;\n"
    "padding: 5px 3px;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.dViewBookingIcon = QtWidgets.QLabel(self.driverPortal)
        self.dViewBookingIcon.setGeometry(QtCore.QRect(270, 240, 101, 71))
        self.dViewBookingIcon.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.dViewBookingIcon.setText("")
        self.dViewBookingIcon.setPixmap(QtGui.QPixmap("../Sketch imgs/viewbooking.png"))
        self.dViewBookingIcon.setScaledContents(True)
        self.dViewBookingIcon.setObjectName("dViewBookingIcon")
        self.welcome = QtWidgets.QLabel(self.driverPortal)
        self.welcome.setGeometry(QtCore.QRect(210, 80, 221, 101))
        self.welcome.setStyleSheet("background-color: none;\n"
    "border: none;")
        self.welcome.setText("")
        self.welcome.setPixmap(QtGui.QPixmap("../Sketch imgs/welcomeAdmin.png"))
        self.welcome.setScaledContents(True)
        self.welcome.setObjectName("welcome")
        self.slogan = QtWidgets.QLabel(self.driverPortal)
        self.slogan.setGeometry(QtCore.QRect(100, 180, 441, 31))
        self.slogan.setStyleSheet("font-family: Roboto;\n"
    "font-style: normal;\n"
    "font-weight: 900;\n"
    "font-size: 14px;\n"
    "text-align: center;\n"
    "border: none;\n"
    "color: white;\n"
    "background-color:none;\n""")
        self.slogan.setObjectName("slogan")
        self.label.raise_()
        self.logoutBtn.raise_()
        self.dViewBookingBtn.raise_()
        self.dServices_txt.raise_()
        self.logo.raise_()
        self.dViewBookingIcon.raise_()
        self.welcome.raise_()
        self.slogan.raise_()

        self.retranslateUi(driverScreen_Dialog)
        QtCore.QMetaObject.connectSlotsByName(driverScreen_Dialog)

    def retranslateUi(self, driverScreen_Dialog):
        _translate = QtCore.QCoreApplication.translate
        driverScreen_Dialog.setWindowTitle(_translate("driverScreen_Dialog", "Dialog"))
        self.dServices_txt.setText(_translate("driverScreen_Dialog", "TAXI DRIVER PORTAL"))
        self.logoutBtn.setText(_translate("driverScreen_Dialog", "LOGOUT"))
        self.dViewBookingBtn.setText(_translate("driverScreen_Dialog", "VIEW OWN BOOKINGS"))
        self.slogan.setText(_translate("driverScreen_Dialog", "<html><head/><body><p align=\"center\">Mind on the "
        "Drive, Hands on the Wheel and Eyes on the Road!</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    driverScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_driverScreen_Dialog()
    ui.driverScreen_setupUi(driverScreen_Dialog)
    driverScreen_Dialog.show()
    sys.exit(app.exec_())
