# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgotPasswordScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import customerLogin

#conn = sqlite3.connect(':memory:')    # testing in memory
conn = sqlite3.connect('taxi.db')   # creates the actual database
c = conn.cursor()    # The cursor to take data to and from the database.


class Ui_forgotPasswordScreen_Dialog(object):
    def __init__(self, Dialog):    # creation of a constructor
        self.Dialog = QtWidgets.QDialog()     # this class has one attribute
        self.forgotPasswordScreen_setupUi(self.Dialog)   # attribute is need to setup the ui

    def its_showtime(self):     # used to show the dialog
        self.Dialog.show()

    def its_closetime(self):   # used to close the dialog
        self.Dialog.close()

    def updatePassword_clicked(self):   # Function to Update Password
        if self.email_txt.text() and  \
           self.email_txt.text() in self.get_customer_info().__str__():
            if self.newPassword_txt.text() == self.verifyPassword_txt.text():  # if password match is true
                self.update_password(self.newPassword_txt.text(),
                                     self.email_txt.text())
                self.showdialog("Congratulations, Your password was successfully updated.")
                self.updatePasswordBtn.setEnabled(False)  # freeze all buttons and fields
                self.email_txt.setEnabled(False)
                self.newPassword_txt.setEnabled(False)
                self.verifyPassword_txt.setEnabled(False)
            else:
                self.password_miss_match_msg("Sorry, your Password does not match.")
        else:
            self.wrong_email_msg("Sorry, your email seems to be Invalid.")

    def get_customer_info(self):
        c.execute("SELECT * FROM Customer WHERE email=:email",
                  {'email': self.email_txt.text()})
        return c.fetchall()  # returns the record from the database

    def update_password(self, password, email):
        with conn:
            c.execute("""UPDATE Customer SET password = :password
                         WHERE email = :email """,
                      {'email': email, 'password': password})

    def showdialog(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Password Updated!")
        msg.setInformativeText(message)
        msg.setWindowTitle("Notification")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def password_miss_match_msg(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Password Error!")
        msg.setInformativeText(message)
        msg.setWindowTitle("Notification")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def wrong_email_msg(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Email Invalid!")
        msg.setInformativeText(message)
        msg.setWindowTitle("Notification")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def backToLogin_clicked(self):   # goes back to the Customer Login Screen
        self.dialog = QtWidgets.QDialog()
        cL = customerLogin.Ui_customerLoginScreen_Dialog(self.dialog)
        cL.its_showtime()
        self.its_closetime()

    def forgotPasswordScreen_setupUi(self, forgotPasswordScreen_Dialog):
        forgotPasswordScreen_Dialog.setObjectName("forgotPasswordScreen_Dialog")
        forgotPasswordScreen_Dialog.resize(671, 460)
        self.forgotPScreen = QtWidgets.QWidget(forgotPasswordScreen_Dialog)
        self.forgotPScreen.setGeometry(QtCore.QRect(10, 10, 651, 441))
        self.forgotPScreen.setStyleSheet("border: 8px solid black;\n"
"background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255), stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n"
"")
        self.forgotPScreen.setObjectName("forgotPScreen")
        self.forgotPassword_label = QtWidgets.QLabel(self.forgotPScreen)
        self.forgotPassword_label.setGeometry(QtCore.QRect(180, 20, 341, 31))
        self.forgotPassword_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 24px;\n"
"border: none;\n"
"background-color: none;\n"
"color: yellow;\n"
"")
        self.forgotPassword_label.setObjectName("forgotPassword_label")
        self.updatePasswordBtn = QtWidgets.QPushButton(self.forgotPScreen,
                                                      clicked=lambda: self.updatePassword_clicked())
        self.updatePasswordBtn.setGeometry(QtCore.QRect(260, 290, 141, 31))
        self.updatePasswordBtn.setStyleSheet("background: #FFFFFF;\n"
"border: 2px solid #0029FF;\n"
"box-sizing: border-box;\n"
"border-radius: 15px;\n"
"font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 12px;\n"
"text-align: center;")
        self.updatePasswordBtn.setObjectName("updatePasswordBtn")
        self.email_txt = QtWidgets.QLineEdit(self.forgotPScreen)
        self.email_txt.setGeometry(QtCore.QRect(290, 190, 211, 20))
        self.email_txt.setStyleSheet("background: #C4C4C4;\n"
"border: 2px solid blue;")
        self.email_txt.setObjectName("email_txt")
        self.newPassword_txt = QtWidgets.QLineEdit(self.forgotPScreen)
        self.newPassword_txt.setGeometry(QtCore.QRect(290, 220, 211, 20))
        self.newPassword_txt.setStyleSheet("background: #C4C4C4;\n"
"border: 2px solid blue;")
        self.newPassword_txt.setObjectName("newPassword_txt")
        self.email_label = QtWidgets.QLabel(self.forgotPScreen)
        self.email_label.setGeometry(QtCore.QRect(140, 190, 51, 16))
        self.email_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 15px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.email_label.setObjectName("email_label")
        self.newPassword_label = QtWidgets.QLabel(self.forgotPScreen)
        self.newPassword_label.setGeometry(QtCore.QRect(140, 220, 111, 16))
        self.newPassword_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 15px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.newPassword_label.setObjectName("newPassword_label")
        self.resetPasswordInstruction_label = QtWidgets.QLabel(self.forgotPScreen)
        self.resetPasswordInstruction_label.setGeometry(QtCore.QRect(90, 90, 461, 61))
        self.resetPasswordInstruction_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 10px;\n"
"text-align: center;\n"
"border: none;\n"
"background-color: none;\n"
"color: white;\n"
"\n"
"")
        self.resetPasswordInstruction_label.setObjectName("resetPasswordInstruction_label")
        self.verifyPassword_label = QtWidgets.QLabel(self.forgotPScreen)
        self.verifyPassword_label.setGeometry(QtCore.QRect(140, 250, 131, 16))
        self.verifyPassword_label.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 15px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.verifyPassword_label.setObjectName("verifyPassword_label")
        self.verifyPassword_txt = QtWidgets.QLineEdit(self.forgotPScreen)
        self.verifyPassword_txt.setGeometry(QtCore.QRect(290, 250, 211, 20))
        self.verifyPassword_txt.setStyleSheet("background: #C4C4C4;\n"
"border: 2px solid blue;")
        self.verifyPassword_txt.setObjectName("verifyPassword_txt")
        self.backToLoginBtn = QtWidgets.QPushButton(self.forgotPScreen,
                                                      clicked=lambda: self.backToLogin_clicked())
        self.backToLoginBtn.setGeometry(QtCore.QRect(510, 390, 111, 31))
        self.backToLoginBtn.setStyleSheet("background:red;\n"
"border: 2px solid blue;\n"
"box-sizing: border-box;\n"
"border-radius: 15px;\n"
"font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 12px;\n"
"text-align: center;\n"
"color: white;\n"
"")
        self.backToLoginBtn.setObjectName("backToLoginBtn")
        self.label = QtWidgets.QLabel(self.forgotPScreen)
        self.label.setGeometry(QtCore.QRect(90, 160, 471, 181))
        self.label.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border: 2px solid rgb(255, 0, 127);\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.forgotPScreen)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 651, 71))
        self.label_2.setStyleSheet("background-color: black;\n"
"border-bottom: 2px solid black;")
        self.label_2.setObjectName("label_2")
        self.logo = QtWidgets.QLabel(self.forgotPScreen)
        self.logo.setGeometry(QtCore.QRect(40, 0, 71, 71))
        self.logo.setStyleSheet("background-color: none;\n"
"border: none;\n"
"padding: 5px 3px;")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.forgetPasswordImg = QtWidgets.QLabel(self.forgotPScreen)
        self.forgetPasswordImg.setGeometry(QtCore.QRect(-10, 340, 271, 101))
        self.forgetPasswordImg.setStyleSheet("background-color: none;\n"
"border: none;")
        self.forgetPasswordImg.setText("")
        self.forgetPasswordImg.setPixmap(QtGui.QPixmap("../Sketch imgs/forgetPassword.png"))
        self.forgetPasswordImg.setScaledContents(True)
        self.forgetPasswordImg.setObjectName("forgetPasswordImg")
        self.label_2.raise_()
        self.label.raise_()
        self.forgotPassword_label.raise_()
        self.updatePasswordBtn.raise_()
        self.email_txt.raise_()
        self.newPassword_txt.raise_()
        self.email_label.raise_()
        self.newPassword_label.raise_()
        self.resetPasswordInstruction_label.raise_()
        self.verifyPassword_label.raise_()
        self.verifyPassword_txt.raise_()
        self.backToLoginBtn.raise_()
        self.logo.raise_()
        self.forgetPasswordImg.raise_()

        self.retranslateUi(forgotPasswordScreen_Dialog)
        QtCore.QMetaObject.connectSlotsByName(forgotPasswordScreen_Dialog)

    def retranslateUi(self, forgotPasswordScreen_Dialog):
        _translate = QtCore.QCoreApplication.translate
        forgotPasswordScreen_Dialog.setWindowTitle(_translate("forgotPasswordScreen_Dialog", "Dialog"))
        self.forgotPassword_label.setText(_translate("forgotPasswordScreen_Dialog", "FORGOT YOUR PASSWORD?"))
        self.updatePasswordBtn.setText(_translate("forgotPasswordScreen_Dialog", "UPDATE PASSWORD"))
        self.email_label.setText(_translate("forgotPasswordScreen_Dialog", "Email"))
        self.newPassword_label.setText(_translate("forgotPasswordScreen_Dialog", "New Password"))
        self.resetPasswordInstruction_label.setText(_translate("forgotPasswordScreen_Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Enter your email, new password, verify your password and click the<br/>update password button to reset your password.</span></p></body></html>"))
        self.verifyPassword_label.setText(_translate("forgotPasswordScreen_Dialog", "Verify Password"))
        self.backToLoginBtn.setText(_translate("forgotPasswordScreen_Dialog", "BACK"))
        self.label_2.setText(_translate("forgotPasswordScreen_Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forgotPasswordScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_forgotPasswordScreen_Dialog()
    ui.forgotPasswordScreen_setupUi(forgotPasswordScreen_Dialog)
    forgotPasswordScreen_Dialog.show()
    sys.exit(app.exec_())
