# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import customerLogin

#conn = sqlite3.connect(':memory:')  # testing in memory
conn = sqlite3.connect('taxi.db')   # creates the actual database
c = conn.cursor()   # The cursor to take data to and from the database.
c.execute("""CREATE TABLE if not exists Customer (
                   customerId INTEGER PRIMARY KEY AUTOINCREMENT,
                   first_name text NOT NULL,
                   last_name text,
                   email text,
                   password text,
                   address text,
                   telephone_no text,
                   cc_number text,
                   cc_exp_date text,
                   cc_cvc text
                   )""")  # creates the table associated with the text field aka line edits

class Ui_registerScreen_Dialog(object):
        def __init__(self, Dialog):    # creation of a constructor
                self.Dialog = QtWidgets.QDialog()   # this class has one attribute
                self.registerScreen_setupUi(self.Dialog)  # attribute is need to setup the ui

        def its_showtime(self):  # used to show the dialog
                self.Dialog.show()

        def its_closetime(self):  # used to close the dialog
                self.Dialog.close()

        def back_button_click(self):
                self.dialog = QtWidgets.QDialog()     # goes back to the Customer Login Screen
                cL = customerLogin.Ui_customerLoginScreen_Dialog(self.dialog)
                cL.its_showtime()
                self.its_closetime()

        def registerAsCustomer_button_click(self):
                self.insert_record()   # inserts the user data
                conn.commit()   # commits the data to the database
                conn.close()   # closes the database connection
                self.disable_fields_and_Buttons()  # function that disables fields and button.
                self.showdialog("Congratulations, you have successfully been registered!")

        def insert_record(self):
                with conn:
                        c.execute(
                                "INSERT INTO Customer VALUES (NULL, :first_name, :last_name, :email, :password, :address, "
                                ":telephone_no, :cc_number, :cc_exp_date, :cc_cvc)",

                                {'customerId': self.customerIDLineEdit.text(),
                                 'first_name': self.firstNameLineEdit.text(),
                                 'last_name': self.LastNameLineEdit.text(),
                                 'email': self.emailLineEdit.text(),
                                 'password': self.passwordLineEdit.text(),
                                 'address': self.addressLineEdit.text(),
                                 'telephone_no': self.telephoneNoLineEdit.text(),
                                 'cc_number': self.ccNumberLineEdit.text(),
                                 'cc_exp_date': self.ccExpDateLineEdit.text(),
                                 'cc_cvc': self.ccCvcLineEdit.text()})

        def disable_fields_and_Buttons(self):
                self.firstNameLineEdit.setEnabled(False) # disable the firstName field
                self.LastNameLineEdit.setEnabled(False) # disable the LastName field
                self.emailLineEdit.setEnabled(False)   # disable the email field
                self.passwordLineEdit.setEnabled(False)  # disable the password field
                self.addressLineEdit.setEnabled(False)  # disable the address field
                self.telephoneNoLineEdit.setEnabled(False)  # disable the telephoneNo field
                self.ccNumberLineEdit.setEnabled(False)  # disable the ccNumber field
                self.ccExpDateLineEdit.setEnabled(False)  # disable the ccExpDate field
                self.ccCvcLineEdit.setEnabled(False)   # disable the ccCvc field
                self.registerAsCustomerBtn.setEnabled(False)  # disable the registerAsCustomerBtn

        def showdialog(self, message):
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("This is a confirmation message.")
                msg.setInformativeText(message)
                msg.setWindowTitle("Confirmation")
                msg.setDetailedText("The details are as follows:" + message)
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                retval = msg.exec_()

        def registerScreen_setupUi(self, registerScreen_Dialog):
                registerScreen_Dialog.setObjectName("registerScreen_Dialog")
                registerScreen_Dialog.resize(671, 460)
                self.registerScreen1 = QtWidgets.QWidget(registerScreen_Dialog)
                self.registerScreen1.setGeometry(QtCore.QRect(10, 10, 651, 441))
                self.registerScreen1.setStyleSheet("border: 8px solid black;\n"
        "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255),"
        " stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n""")
                self.registerScreen1.setObjectName("registerScreen1")
                self.register_txt = QtWidgets.QLabel(self.registerScreen1)
                self.register_txt.setGeometry(QtCore.QRect(190, 20, 341, 31))
                self.register_txt.setStyleSheet("font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 24px;\n"
        "border: none;\n"
        "background-color: none;\n"
        "color: yellow;\n""")
                self.register_txt.setObjectName("register_txt")
                self.backBtn = QtWidgets.QPushButton(self.registerScreen1,
                                                     clicked=lambda: self.back_button_click())
                self.backBtn.setGeometry(QtCore.QRect(540, 390, 91, 31))
                self.backBtn.setStyleSheet("background: red;\n"
        "border: 3px solid blue;\n"
        "box-sizing: border-box;\n"
        "border-radius: 15px;\n"
        "font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: white;")
                self.backBtn.setObjectName("backBtn")
                self.registerAsCustomerBtn = QtWidgets.QPushButton(self.registerScreen1,
                                                           clicked=lambda: self.registerAsCustomer_button_click())
                self.registerAsCustomerBtn.setGeometry(QtCore.QRect(380, 290, 161, 31))
                self.registerAsCustomerBtn.setStyleSheet("background: blue;\n"
        "border: 2px solid rgb(255, 0, 127);\n"
        "box-sizing: border-box;\n"
        "border-radius: 10px;\n"
        "font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: white;")
                self.registerAsCustomerBtn.setObjectName("registerAsCustomerBtn")
                self.label = QtWidgets.QLabel(self.registerScreen1)
                self.label.setGeometry(QtCore.QRect(0, 0, 651, 71))
                self.label.setStyleSheet("background-color: black;\n"
        "border-bottom: 2px solid black;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.firstNameLabel = QtWidgets.QLabel(self.registerScreen1)
                self.firstNameLabel.setGeometry(QtCore.QRect(50, 190, 91, 21))
                self.firstNameLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.firstNameLabel.setObjectName("firstNameLabel")
                self.emailLabel = QtWidgets.QLabel(self.registerScreen1)
                self.emailLabel.setGeometry(QtCore.QRect(50, 250, 91, 21))
                self.emailLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.emailLabel.setObjectName("emailLabel")
                self.addressLabel = QtWidgets.QLabel(self.registerScreen1)
                self.addressLabel.setGeometry(QtCore.QRect(50, 310, 91, 21))
                self.addressLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.addressLabel.setObjectName("addressLabel")
                self.telephoneNoLabel = QtWidgets.QLabel(self.registerScreen1)
                self.telephoneNoLabel.setGeometry(QtCore.QRect(330, 160, 101, 21))
                self.telephoneNoLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.telephoneNoLabel.setObjectName("telephoneNoLabel")
                self.ccNumberLabel = QtWidgets.QLabel(self.registerScreen1)
                self.ccNumberLabel.setGeometry(QtCore.QRect(330, 190, 81, 21))
                self.ccNumberLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.ccNumberLabel.setObjectName("ccNumberLabel")
                self.LastNameLabel = QtWidgets.QLabel(self.registerScreen1)
                self.LastNameLabel.setGeometry(QtCore.QRect(50, 220, 91, 21))
                self.LastNameLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.LastNameLabel.setObjectName("LastNameLabel")
                self.passwordLabel = QtWidgets.QLabel(self.registerScreen1)
                self.passwordLabel.setGeometry(QtCore.QRect(50, 280, 91, 21))
                self.passwordLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.passwordLabel.setObjectName("passwordLabel")
                self.ccExpDateLabel = QtWidgets.QLabel(self.registerScreen1)
                self.ccExpDateLabel.setGeometry(QtCore.QRect(330, 220, 91, 21))
                self.ccExpDateLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.ccExpDateLabel.setObjectName("ccExpDateLabel")
                self.ccCvc = QtWidgets.QLabel(self.registerScreen1)
                self.ccCvc.setGeometry(QtCore.QRect(330, 250, 61, 21))
                self.ccCvc.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.ccCvc.setObjectName("ccCvc")
                self.telephoneNoLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.telephoneNoLineEdit.setGeometry(QtCore.QRect(440, 160, 161, 20))
                self.telephoneNoLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.telephoneNoLineEdit.setObjectName("telephoneNoLineEdit")
                self.addressLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.addressLineEdit.setGeometry(QtCore.QRect(150, 310, 161, 20))
                self.addressLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.addressLineEdit.setObjectName("addressLineEdit")
                self.passwordLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.passwordLineEdit.setGeometry(QtCore.QRect(150, 280, 161, 20))
                self.passwordLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.passwordLineEdit.setObjectName("passwordLineEdit")
                self.emailLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.emailLineEdit.setGeometry(QtCore.QRect(150, 250, 161, 20))
                self.emailLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.emailLineEdit.setObjectName("emailLineEdit")
                self.LastNameLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.LastNameLineEdit.setGeometry(QtCore.QRect(150, 220, 161, 20))
                self.LastNameLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.LastNameLineEdit.setObjectName("LastNameLineEdit")
                self.firstNameLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.firstNameLineEdit.setGeometry(QtCore.QRect(150, 190, 161, 20))
                self.firstNameLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.firstNameLineEdit.setText("")
                self.firstNameLineEdit.setObjectName("firstNameLineEdit")
                self.ccNumberLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.ccNumberLineEdit.setGeometry(QtCore.QRect(440, 190, 161, 20))
                self.ccNumberLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.ccNumberLineEdit.setObjectName("ccNumberLineEdit")
                self.ccExpDateLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.ccExpDateLineEdit.setGeometry(QtCore.QRect(440, 220, 161, 20))
                self.ccExpDateLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.ccExpDateLineEdit.setObjectName("ccExpDateLineEdit")
                self.ccCvcLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.ccCvcLineEdit.setGeometry(QtCore.QRect(440, 250, 161, 20))
                self.ccCvcLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.ccCvcLineEdit.setObjectName("ccCvcLineEdit")
                self.label_11 = QtWidgets.QLabel(self.registerScreen1)
                self.label_11.setGeometry(QtCore.QRect(30, 140, 591, 211))
                self.label_11.setStyleSheet("border: 2px solid rgb(255, 0, 127);\n"
        "background-color: rgb(149, 200, 255);")
                self.label_11.setText("")
                self.label_11.setObjectName("label_11")
                self.registerSlogan = QtWidgets.QLabel(self.registerScreen1)
                self.registerSlogan.setGeometry(QtCore.QRect(160, 100, 321, 16))
                self.registerSlogan.setStyleSheet("font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 15px;\n"
        "text-align: center;\n"
        "border: none;\n"
        "color: white;\n"
        "background-color: none;\n""")
                self.registerSlogan.setObjectName("registerSlogan")
                self.customerIDLineEdit = QtWidgets.QLineEdit(self.registerScreen1)
                self.customerIDLineEdit.setGeometry(QtCore.QRect(150, 160, 161, 20))
                self.customerIDLineEdit.setStyleSheet("background: red;\n"
        "border: 1px solid blue;")
                self.customerIDLineEdit.setText("")
                self.customerIDLineEdit.setObjectName("customerIDLineEdit")
                self.customerIDLineEdit.setEnabled(False)
                self.customerIDLabel = QtWidgets.QLabel(self.registerScreen1)
                self.customerIDLabel.setGeometry(QtCore.QRect(50, 160, 91, 21))
                self.customerIDLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 14px;\n"
        "text-align: center;\n"
        "color: red;\n"
        "border: none;\n"
        "background-color: none;")
                self.customerIDLabel.setObjectName("customerIDLabel")
                self.logo = QtWidgets.QLabel(self.registerScreen1)
                self.logo.setGeometry(QtCore.QRect(40, 0, 71, 71))
                self.logo.setStyleSheet("background-color: none;\n"
        "border: none;\n"
        "padding: 5px 3px;")
                self.logo.setText("")
                self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
                self.logo.setScaledContents(True)
                self.logo.setObjectName("logo")
                self.logo_2 = QtWidgets.QLabel(self.registerScreen1)
                self.logo_2.setGeometry(QtCore.QRect(30, 360, 101, 61))
                self.logo_2.setStyleSheet("background-color: none;\n"
        "border: none;")
                self.logo_2.setText("")
                self.logo_2.setPixmap(QtGui.QPixmap("../Sketch imgs/registerNow.png"))
                self.logo_2.setScaledContents(True)
                self.logo_2.setObjectName("logo_2")
                self.label_2 = QtWidgets.QLabel(self.registerScreen1)
                self.label_2.setGeometry(QtCore.QRect(190, 160, 91, 20))
                self.label_2.setStyleSheet("background-color: none;\n"
        "border: none;")
                self.label_2.setObjectName("label_2")
                self.label.raise_()
                self.label_11.raise_()
                self.backBtn.raise_()
                self.registerAsCustomerBtn.raise_()
                self.register_txt.raise_()
                self.firstNameLabel.raise_()
                self.emailLabel.raise_()
                self.addressLabel.raise_()
                self.telephoneNoLabel.raise_()
                self.ccNumberLabel.raise_()
                self.LastNameLabel.raise_()
                self.passwordLabel.raise_()
                self.ccExpDateLabel.raise_()
                self.ccCvc.raise_()
                self.telephoneNoLineEdit.raise_()
                self.addressLineEdit.raise_()
                self.passwordLineEdit.raise_()
                self.emailLineEdit.raise_()
                self.LastNameLineEdit.raise_()
                self.firstNameLineEdit.raise_()
                self.ccNumberLineEdit.raise_()
                self.ccExpDateLineEdit.raise_()
                self.ccCvcLineEdit.raise_()
                self.registerSlogan.raise_()
                self.customerIDLineEdit.raise_()
                self.customerIDLabel.raise_()
                self.logo.raise_()
                self.logo_2.raise_()
                self.label_2.raise_()

                self.retranslateUi(registerScreen_Dialog)
                QtCore.QMetaObject.connectSlotsByName(registerScreen_Dialog)

        def retranslateUi(self, registerScreen_Dialog):
                _translate = QtCore.QCoreApplication.translate
                registerScreen_Dialog.setWindowTitle(_translate("registerScreen_Dialog", "Dialog"))
                self.register_txt.setText(_translate("registerScreen_Dialog", "CUSTOMER REGISTRATION"))
                self.backBtn.setText(_translate("registerScreen_Dialog", "BACK"))
                self.registerAsCustomerBtn.setText(_translate("registerScreen_Dialog", "Register as Customer"))
                self.firstNameLabel.setText(_translate("registerScreen_Dialog", "First Name"))
                self.emailLabel.setText(_translate("registerScreen_Dialog", "Email"))
                self.addressLabel.setText(_translate("registerScreen_Dialog", "Address"))
                self.telephoneNoLabel.setText(_translate("registerScreen_Dialog", "Telephone No"))
                self.ccNumberLabel.setText(_translate("registerScreen_Dialog", "CC Number"))
                self.LastNameLabel.setText(_translate("registerScreen_Dialog", "Last Name"))
                self.passwordLabel.setText(_translate("registerScreen_Dialog", "Password"))
                self.ccExpDateLabel.setText(_translate("registerScreen_Dialog", "CC Exp Date"))
                self.ccCvc.setText(_translate("registerScreen_Dialog", "CC CVC"))
                self.registerSlogan.setText(_translate("registerScreen_Dialog", "REGISTER NOW & NEVER BE LATE AGAIN!!"))
                self.customerIDLabel.setText(_translate("registerScreen_Dialog", "Customer ID"))
                self.label_2.setText(_translate("registerScreen_Dialog", "Auto Generated"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_registerScreen_Dialog()
    ui.registerScreen_setupUi(registerScreen_Dialog)
    registerScreen_Dialog.show()
    sys.exit(app.exec_())
