# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateABooking.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

#conn = sqlite3.connect(':memory:') # testing in memory
conn = sqlite3.connect('taxi.db')
c = conn.cursor()

class Ui_makeBookingScreen_Dialog(object):

    # def __init__(self, Dialog):
    #     self.Dialog = QtWidgets.QDialog()
    #     self.makeBookingScreen_setupUi(self.Dialog)
    #
    # def its_showtime(self):
    #     self.Dialog.show()
    #
    # def its_closetime(self):
    #     self.Dialog.close()

    # def __init__(self):
    #     self.newPassword_txt = None

    def updateNowBtn_click(self):
        if self.BookingIDLineEdit.text() in self.get_booking_info().__str__():
                 self.update_booking(self.BookingIDLineEdit.text(),
                                     self.dateBookedLineEdit.text(),
                                     self.PickUpAddressLineEdit.text(),
                                     self.dropOffAddressLineEdit.text(),
                                     self.pickUpTimeLineEdit.text(),
                                     self.pickUpDateLineEdit.text())
                 self.showdialog("Your password was successfully updated.")
                 self.updateNowBtn.setEnabled(False)  # freeze all buttons and fields
                 self.PickUpAddressLineEdit.setEnabled(False)
                 self.dropOffAddressLineEdit.setEnabled(False)
                 self.pickUpTimeLineEdit.setEnabled(False)
        else:
            self.showdialog("Email not found in Customer Table")

    def get_booking_info(self):
        c.execute("SELECT * FROM Booking WHERE bookingId=:bookingId",
                  {'bookingId': self.BookingIDLineEdit.text()})
        return c.fetchall()  # returns the record from the database

    def update_booking(self, bookingId, dateBooked, PickUpAddress, dropOffAddress, pickUpTime, pickUpDate):
        with conn:
            c.execute("""UPDATE Booking SET bookingId= :bookingId, dateBooked= :dateBooked, pickUpAddress= :pickUpAddress, dropOffAddress= :dropOffAddress
                         ,pickUpTime= :pickUpTime , pickUpDate= :pickUpDate
                         WHERE bookingId = :bookingId """,
                      {'bookingId': bookingId, 'dateBooked': dateBooked, 'pickUpAddress' :PickUpAddress,
                       'dropOffAddress': dropOffAddress, 'pickUpTime': pickUpTime, 'pickUpDate':pickUpDate})
    def showdialog(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Password")
        msg.setInformativeText(message)
        msg.setWindowTitle("Password Updated")
        msg.setDetailedText("The details are as follows:" + message)
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        retval = msg.exec_()

    def makeBookingScreen_setupUi(self, makeBookingScreen_Dialog):
        makeBookingScreen_Dialog.setObjectName("makeBookingScreen_Dialog")
        makeBookingScreen_Dialog.resize(578, 400)
        self.makeABookingScreen = QtWidgets.QWidget(makeBookingScreen_Dialog)
        self.makeABookingScreen.setGeometry(QtCore.QRect(10, 10, 561, 381))
        self.makeABookingScreen.setStyleSheet("border: 3px solid blue;\n"
"background-color: yellow;")
        self.makeABookingScreen.setObjectName("makeABookingScreen")
        self.make_txt = QtWidgets.QLabel(self.makeABookingScreen)
        self.make_txt.setGeometry(QtCore.QRect(160, 20, 251, 21))
        self.make_txt.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 24px;\n"
"border: none;\n"
"background-color: none;\n"
"color: yellow;\n"
"")
        self.make_txt.setObjectName("make_txt")
        self.backBtn = QtWidgets.QPushButton(self.makeABookingScreen)
        self.backBtn.setGeometry(QtCore.QRect(460, 340, 91, 31))
        self.backBtn.setStyleSheet("background: red;\n"
"border: 3px solid blue;\n"
"box-sizing: border-box;\n"
"border-radius: 15px;\n"
"font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 13px;\n"
"text-align: center;\n"
"color: white;")
        self.backBtn.setObjectName("backBtn")
        self.updateNowBtn = QtWidgets.QPushButton(self.makeABookingScreen, clicked=lambda: self.updateNowBtn_click())
        self.updateNowBtn.setGeometry(QtCore.QRect(380, 150, 161, 31))
        self.updateNowBtn.setStyleSheet("background: blue;\n"
"border: 2px solid rgb(255, 0, 127);\n"
"box-sizing: border-box;\n"
"border-radius: 10px;\n"
"font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight:500;\n"
"font-size: 13px;\n"
"text-align: center;\n"
"color: white;")
        self.updateNowBtn.setObjectName("updateNowBtn")
        self.label = QtWidgets.QLabel(self.makeABookingScreen)
        self.label.setGeometry(QtCore.QRect(0, 0, 561, 61))
        self.label.setStyleSheet("background-color: black;\n"
"border-bottom: 2px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.dateBookedLabel = QtWidgets.QLabel(self.makeABookingScreen)
        self.dateBookedLabel.setGeometry(QtCore.QRect(20, 160, 91, 21))
        self.dateBookedLabel.setStyleSheet("font-family: Roboto;\n"
"font-style:normal;\n"
"font-weight:500;\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.dateBookedLabel.setObjectName("dateBookedLabel")
        self.dropOffAddresslLabel = QtWidgets.QLabel(self.makeABookingScreen)
        self.dropOffAddresslLabel.setGeometry(QtCore.QRect(20, 220, 131, 21))
        self.dropOffAddresslLabel.setStyleSheet("font-family: Roboto;\n"
"font-style:normal;\n"
"font-weight:500;\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.dropOffAddresslLabel.setObjectName("dropOffAddresslLabel")
        self.pickUpDateLabel = QtWidgets.QLabel(self.makeABookingScreen)
        self.pickUpDateLabel.setGeometry(QtCore.QRect(20, 280, 91, 21))
        self.pickUpDateLabel.setStyleSheet("font-family: Roboto;\n"
"font-style:normal;\n"
"font-weight:500;\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.pickUpDateLabel.setObjectName("pickUpDateLabel")
        self.pickUpAddressLabel = QtWidgets.QLabel(self.makeABookingScreen)
        self.pickUpAddressLabel.setGeometry(QtCore.QRect(20, 190, 121, 21))
        self.pickUpAddressLabel.setStyleSheet("font-family: Roboto;\n"
"font-style:normal;\n"
"font-weight:500;\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.pickUpAddressLabel.setObjectName("pickUpAddressLabel")
        self.pickUpTimeLabel = QtWidgets.QLabel(self.makeABookingScreen)
        self.pickUpTimeLabel.setGeometry(QtCore.QRect(20, 250, 101, 21))
        self.pickUpTimeLabel.setStyleSheet("font-family: Roboto;\n"
"font-style:normal;\n"
"font-weight:500;\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.pickUpTimeLabel.setObjectName("pickUpTimeLabel")
        self.dropOffAddressLineEdit = QtWidgets.QLineEdit(self.makeABookingScreen)
        self.dropOffAddressLineEdit.setGeometry(QtCore.QRect(150, 220, 211, 20))
        self.dropOffAddressLineEdit.setStyleSheet("background: #C4C4C4;\n"
"border: 1px solid blue;")
        self.dropOffAddressLineEdit.setObjectName("dropOffAddressLineEdit")
        self.PickUpAddressLineEdit = QtWidgets.QLineEdit(self.makeABookingScreen)
        self.PickUpAddressLineEdit.setGeometry(QtCore.QRect(150, 190, 211, 20))
        self.PickUpAddressLineEdit.setStyleSheet("background: #C4C4C4;\n"
"border: 1px solid blue;")
        self.PickUpAddressLineEdit.setObjectName("PickUpAddressLineEdit")
        self.label_11 = QtWidgets.QLabel(self.makeABookingScreen)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 541, 221))
        self.label_11.setStyleSheet("border: 2px solid rgb(255, 0, 127);\n"
"background-color: rgb(149, 200, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.makeSlogan = QtWidgets.QLabel(self.makeABookingScreen)
        self.makeSlogan.setGeometry(QtCore.QRect(230, 80, 121, 20))
        self.makeSlogan.setStyleSheet("font-family: Roboto;\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 15px;\n"
"text-align: center;\n"
"border: none;\n"
"color:red;\n"
"")
        self.makeSlogan.setObjectName("makeSlogan")
        self.pickUpTimeLineEdit = QtWidgets.QTimeEdit(self.makeABookingScreen)
        self.pickUpTimeLineEdit.setGeometry(QtCore.QRect(150, 250, 211, 22))
        self.pickUpTimeLineEdit.setStyleSheet("background: #C4C4C4;\n"
"border: 1px solid blue;")
        self.pickUpTimeLineEdit.setObjectName("pickUpTimeLineEdit")
        self.pickUpDateLineEdit = QtWidgets.QDateEdit(self.makeABookingScreen)
        self.pickUpDateLineEdit.setGeometry(QtCore.QRect(150, 280, 211, 22))
        self.pickUpDateLineEdit.setStyleSheet("background: #C4C4C4;\n"
"border: 1px solid blue;")
        self.pickUpDateLineEdit.setObjectName("pickUpDateLineEdit")
        self.dateBookedLineEdit = QtWidgets.QDateEdit(self.makeABookingScreen)
        self.dateBookedLineEdit.setGeometry(QtCore.QRect(150, 160, 211, 22))
        self.dateBookedLineEdit.setStyleSheet("background: #C4C4C4;\n"
"border: 1px solid blue;")
        self.dateBookedLineEdit.setObjectName("dateBookedLineEdit")
        self.BookingIDLineEdit = QtWidgets.QLineEdit(self.makeABookingScreen)
        self.BookingIDLineEdit.setGeometry(QtCore.QRect(150, 130, 211, 20))
        self.BookingIDLineEdit.setStyleSheet("background: #C4C4C4;\n"
"border: 1px solid blue;")
        self.BookingIDLineEdit.setObjectName("BookingIDLineEdit")
        self.dateBookedLabel_2 = QtWidgets.QLabel(self.makeABookingScreen)
        self.dateBookedLabel_2.setGeometry(QtCore.QRect(20, 130, 91, 21))
        self.dateBookedLabel_2.setStyleSheet("font-family: Roboto;\n"
"font-style:normal;\n"
"font-weight:500;\n"
"font-size: 14px;\n"
"text-align: center;\n"
"color: #000000;\n"
"border: none;\n"
"background-color: none;")
        self.dateBookedLabel_2.setObjectName("dateBookedLabel_2")
        self.label_11.raise_()
        self.label.raise_()
        self.backBtn.raise_()
        self.updateNowBtn.raise_()
        self.make_txt.raise_()
        self.dateBookedLabel.raise_()
        self.dropOffAddresslLabel.raise_()
        self.pickUpDateLabel.raise_()
        self.pickUpAddressLabel.raise_()
        self.pickUpTimeLabel.raise_()
        self.dropOffAddressLineEdit.raise_()
        self.PickUpAddressLineEdit.raise_()
        self.makeSlogan.raise_()
        self.pickUpTimeLineEdit.raise_()
        self.pickUpDateLineEdit.raise_()
        self.dateBookedLineEdit.raise_()
        self.BookingIDLineEdit.raise_()
        self.dateBookedLabel_2.raise_()

        self.retranslateUi(makeBookingScreen_Dialog)
        QtCore.QMetaObject.connectSlotsByName(makeBookingScreen_Dialog)

    def retranslateUi(self, makeBookingScreen_Dialog):
        _translate = QtCore.QCoreApplication.translate
        makeBookingScreen_Dialog.setWindowTitle(_translate("makeBookingScreen_Dialog", "Dialog"))
        self.make_txt.setText(_translate("makeBookingScreen_Dialog", "UPDATE A BOOKING"))
        self.backBtn.setText(_translate("makeBookingScreen_Dialog", "BACK"))
        self.updateNowBtn.setText(_translate("makeBookingScreen_Dialog", "UPDATE NOW"))
        self.dateBookedLabel.setText(_translate("makeBookingScreen_Dialog", "Date Booked"))
        self.dropOffAddresslLabel.setText(_translate("makeBookingScreen_Dialog", "Drop Off Address"))
        self.pickUpDateLabel.setText(_translate("makeBookingScreen_Dialog", "Pick Up Date"))
        self.pickUpAddressLabel.setText(_translate("makeBookingScreen_Dialog", "Pick Up Address"))
        self.pickUpTimeLabel.setText(_translate("makeBookingScreen_Dialog", "Pick Up Time"))
        self.makeSlogan.setText(_translate("makeBookingScreen_Dialog", "UPDATE NOW!!!"))
        self.dateBookedLabel_2.setText(_translate("makeBookingScreen_Dialog", "Booking ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    makeBookingScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_makeBookingScreen_Dialog()
    ui.makeBookingScreen_setupUi(makeBookingScreen_Dialog)
    makeBookingScreen_Dialog.show()
    sys.exit(app.exec_())
