# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewABooking.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import customerServices

conn = sqlite3.connect('taxi.db')   # creates the actual database
c = conn.cursor()   # The cursor to take data to and from the database.

class Ui_viewBookingScreen_Dialog(object):

        def __init__(self, Dialog):   # creation of a constructor
                self.Dialog = QtWidgets.QDialog()   # this class has one attribute
                self.viewBookingScreen_setupUi(self.Dialog)    # attribute is need to setup the ui

        def its_showtime(self):   # used to show the dialog
                self.Dialog.show()

        def its_closetime(self):    # used to close the dialog
                self.Dialog.close()

        def back_click(self):    # goes back to the Customer Services Screen
                self.dialog = QtWidgets.QDialog()
                cS = customerServices.Ui_CustomerPortal(self.dialog)
                cS.its_showtime()
                self.its_closetime()

        def get_customer_info(self):    # gets the BookingId from the Booking table.
                c.execute("SELECT * FROM Booking WHERE bookingId=:bookingId",
                          {'bookingId': self.bookingIdLineEdit.text()})
                return c.fetchall()  # returns the record from the database

        def viewall(self):
                if self.bookingIdLineEdit.text() and \
                   self.bookingIdLineEdit.text() in self.get_customer_info().__str__():
                 List = self.get_customer_info()
                 self.showdialog("Congratulations, your booking was successfully found, you may now view your booking!")
                 self.bookingIdLineEdit.setEnabled(False)      # function that disable field.
                 self.viewNowBtn.setEnabled(False)    # function that disable button.

                 self.bookingIdLineEdit.setText(str(List[0][0]))
                 self.dateBookedLineEdit.setText(List[0][5])
                 self.PickUpAddressLineEdit.setText(List[0][6])
                 self.dropOffAddressLineEdit.setText(List[0][7])
                 self.pickUpTimeLineEdit.setText(List[0][8])
                 self.dropOffAddressLineEdit_2.setText(List[0][9])
                else:
                     self.wrongBookingID("Sorry, your BookingID is Invalid.")

        def showdialog(self, message):
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("This is a confirmation message.")
                msg.setInformativeText(message)
                msg.setWindowTitle("Confirmation")
                msg.setDetailedText("The details are as follows:" + message)
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                retval = msg.exec_()

        def wrongBookingID(self, message):
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Inavlid BookingID.")
                msg.setInformativeText(message)
                msg.setWindowTitle("Notification")
                msg.setDetailedText("The details are as follows:" + message)
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
                retval = msg.exec_()

        def viewBookingScreen_setupUi(self, viewBookingScreen_Dialog):
                viewBookingScreen_Dialog.setObjectName("viewBookingScreen_Dialog")
                viewBookingScreen_Dialog.resize(671, 460)
                self.viewABookingScreen = QtWidgets.QWidget(viewBookingScreen_Dialog)
                self.viewABookingScreen.setGeometry(QtCore.QRect(10, 10, 651, 441))
                self.viewABookingScreen.setStyleSheet("border: 8px solid black;\n"
        "background-color:qlineargradient(spread:pad, x1:0.0511364, y1:1, x2:0, y2:0, stop:0 rgba(251, 255, 0, 255), "
        "stop:0.98 rgba(0, 61, 255, 255), stop:1 rgba(0, 0, 0, 0));\n" "")
                self.viewABookingScreen.setObjectName("viewABookingScreen")
                self.view_txt = QtWidgets.QLabel(self.viewABookingScreen)
                self.view_txt.setGeometry(QtCore.QRect(230, 10, 191, 51))
                self.view_txt.setStyleSheet("font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 24px;\n"
        "border: none;\n"
        "background-color: none;\n"
        "color: yellow;\n""")
                self.view_txt.setObjectName("view_txt")
                self.backBtn = QtWidgets.QPushButton(self.viewABookingScreen,
                                                clicked=lambda: self.back_click())
                self.backBtn.setGeometry(QtCore.QRect(530, 390, 91, 31))
                self.backBtn.setStyleSheet("background: red;\n"
        "border: 3px solid blue;\n"
        "box-sizing: border-box;\n"
        "border-radius: 15px;\n"
        "font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: white;")
                self.backBtn.setObjectName("backBtn")
                self.viewNowBtn = QtWidgets.QPushButton(self.viewABookingScreen,
                                                clicked=lambda: self.viewall())
                self.viewNowBtn.setGeometry(QtCore.QRect(250, 320, 131, 31))
                self.viewNowBtn.setStyleSheet("background: blue;\n"
        "border: 2px solid rgb(255, 0, 127);\n"
        "box-sizing: border-box;\n"
        "border-radius: 10px;\n"
        "font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: white;")
                self.viewNowBtn.setObjectName("viewNowBtn")
                self.label = QtWidgets.QLabel(self.viewABookingScreen)
                self.label.setGeometry(QtCore.QRect(0, 0, 651, 71))
                self.label.setStyleSheet("background-color: black;\n"
        "border-bottom: 2px solid black;")
                self.label.setText("")
                self.label.setObjectName("label")
                self.dateBookedLabel = QtWidgets.QLabel(self.viewABookingScreen)
                self.dateBookedLabel.setGeometry(QtCore.QRect(40, 240, 91, 21))
                self.dateBookedLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.dateBookedLabel.setObjectName("dateBookedLabel")
                self.dropOffAddresslLabel = QtWidgets.QLabel(self.viewABookingScreen)
                self.dropOffAddresslLabel.setGeometry(QtCore.QRect(330, 210, 121, 21))
                self.dropOffAddresslLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.dropOffAddresslLabel.setObjectName("dropOffAddresslLabel")
                self.pickUpDateLabel = QtWidgets.QLabel(self.viewABookingScreen)
                self.pickUpDateLabel.setGeometry(QtCore.QRect(330, 270, 91, 21))
                self.pickUpDateLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.pickUpDateLabel.setObjectName("pickUpDateLabel")
                self.pickUpAddressLabel = QtWidgets.QLabel(self.viewABookingScreen)
                self.pickUpAddressLabel.setGeometry(QtCore.QRect(40, 270, 121, 21))
                self.pickUpAddressLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.pickUpAddressLabel.setObjectName("pickUpAddressLabel")
                self.pickUpTimeLabel = QtWidgets.QLabel(self.viewABookingScreen)
                self.pickUpTimeLabel.setGeometry(QtCore.QRect(330, 240, 101, 21))
                self.pickUpTimeLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.pickUpTimeLabel.setObjectName("pickUpTimeLabel")
                self.dropOffAddressLineEdit = QtWidgets.QLineEdit(self.viewABookingScreen)
                self.dropOffAddressLineEdit.setGeometry(QtCore.QRect(450, 210, 161, 20))
                self.dropOffAddressLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.dropOffAddressLineEdit.setObjectName("dropOffAddressLineEdit")
                self.dropOffAddressLineEdit.setEnabled(False)
                self.PickUpAddressLineEdit = QtWidgets.QLineEdit(self.viewABookingScreen)
                self.PickUpAddressLineEdit.setGeometry(QtCore.QRect(150, 270, 161, 20))
                self.PickUpAddressLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.PickUpAddressLineEdit.setObjectName("PickUpAddressLineEdit")
                self.PickUpAddressLineEdit.setEnabled(False)
                self.pickUpDateLineEdit_2 = QtWidgets.QLabel(self.viewABookingScreen)
                self.pickUpDateLineEdit_2.setGeometry(QtCore.QRect(30, 140, 591, 221))
                self.pickUpDateLineEdit_2.setStyleSheet("border: 2px solid rgb(255, 0, 127);\n"
        "background-color: rgb(149, 200, 255);")
                self.pickUpDateLineEdit_2.setText("")
                self.pickUpDateLineEdit_2.setEnabled(False)
                self.pickUpDateLineEdit_2.setObjectName("pickUpDateLineEdit_2")
                self.viewSlogan = QtWidgets.QLabel(self.viewABookingScreen)
                self.viewSlogan.setGeometry(QtCore.QRect(200, 90, 231, 41))
                self.viewSlogan.setStyleSheet("font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 15px;\n"
        "text-align: center;\n"
        "border: none;\n"
        "color:white;\n"
        "background-color: none;\n""")
                self.viewSlogan.setObjectName("viewSlogan")
                self.dropOffAddressLineEdit_2 = QtWidgets.QLineEdit(self.viewABookingScreen)
                self.dropOffAddressLineEdit_2.setGeometry(QtCore.QRect(450, 270, 161, 20))
                self.dropOffAddressLineEdit_2.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.dropOffAddressLineEdit_2.setObjectName("dropOffAddressLineEdit_2")
                self.dropOffAddressLineEdit_2.setEnabled(False)
                self.pickUpTimeLineEdit = QtWidgets.QLineEdit(self.viewABookingScreen)
                self.pickUpTimeLineEdit.setGeometry(QtCore.QRect(450, 240, 161, 20))
                self.pickUpTimeLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.pickUpTimeLineEdit.setObjectName("pickUpTimeLineEdit")
                self.pickUpTimeLineEdit.setEnabled(False)
                self.dateBookedLineEdit = QtWidgets.QLineEdit(self.viewABookingScreen)
                self.dateBookedLineEdit.setGeometry(QtCore.QRect(150, 240, 161, 20))
                self.dateBookedLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.dateBookedLineEdit.setObjectName("dateBookedLineEdit")
                self.dateBookedLineEdit.setEnabled(False)
                self.bookingIdLabel = QtWidgets.QLabel(self.viewABookingScreen)
                self.bookingIdLabel.setGeometry(QtCore.QRect(40, 210, 91, 21))
                self.bookingIdLabel.setStyleSheet("font-family: Roboto;\n"
        "font-style:normal;\n"
        "font-weight:500;\n"
        "font-size: 13px;\n"
        "text-align: center;\n"
        "color: #000000;\n"
        "border: none;\n"
        "background-color: none;")
                self.bookingIdLabel.setObjectName("bookingIdLabel")
                self.bookingIdLineEdit = QtWidgets.QLineEdit(self.viewABookingScreen)
                self.bookingIdLineEdit.setGeometry(QtCore.QRect(150, 210, 161, 20))
                self.bookingIdLineEdit.setStyleSheet("background: #C4C4C4;\n"
        "border: 1px solid blue;")
                self.bookingIdLineEdit.setObjectName("bookingIdLineEdit")
                self.logo = QtWidgets.QLabel(self.viewABookingScreen)
                self.logo.setGeometry(QtCore.QRect(40, 0, 71, 71))
                self.logo.setStyleSheet("background-color: none;\n"
        "border: none;\n"
        "padding: 5px 3px;")
                self.logo.setText("")
                self.logo.setPixmap(QtGui.QPixmap("../Sketch imgs/official-taxi-logo.png"))
                self.logo.setScaledContents(True)
                self.logo.setObjectName("logo")
                self.logo_2 = QtWidgets.QLabel(self.viewABookingScreen)
                self.logo_2.setGeometry(QtCore.QRect(30, 380, 101, 41))
                self.logo_2.setStyleSheet("background-color: none;\n"
        "border: none;")
                self.logo_2.setText("")
                self.logo_2.setPixmap(QtGui.QPixmap("../Sketch imgs/eye.png"))
                self.logo_2.setScaledContents(True)
                self.logo_2.setObjectName("logo_2")
                self.viewInstruction = QtWidgets.QLabel(self.viewABookingScreen)
                self.viewInstruction.setGeometry(QtCore.QRect(130, 150, 391, 31))
                self.viewInstruction.setStyleSheet("font-family: Roboto;\n"
        "font-style: normal;\n"
        "font-weight: 900;\n"
        "font-size: 15px;\n"
        "text-align: center;\n"
        "border: none;\n"
        "color:black;\n"
        "background-color: none;\n""")
                self.viewInstruction.setObjectName("viewInstruction")
                self.pickUpDateLineEdit_2.raise_()
                self.label.raise_()
                self.backBtn.raise_()
                self.viewNowBtn.raise_()
                self.view_txt.raise_()
                self.dateBookedLabel.raise_()
                self.dropOffAddresslLabel.raise_()
                self.pickUpDateLabel.raise_()
                self.pickUpAddressLabel.raise_()
                self.pickUpTimeLabel.raise_()
                self.dropOffAddressLineEdit.raise_()
                self.PickUpAddressLineEdit.raise_()
                self.viewSlogan.raise_()
                self.dropOffAddressLineEdit_2.raise_()
                self.pickUpTimeLineEdit.raise_()
                self.dateBookedLineEdit.raise_()
                self.bookingIdLabel.raise_()
                self.bookingIdLineEdit.raise_()
                self.logo.raise_()
                self.logo_2.raise_()
                self.viewInstruction.raise_()

                self.retranslateUi(viewBookingScreen_Dialog)
                QtCore.QMetaObject.connectSlotsByName(viewBookingScreen_Dialog)

        def retranslateUi(self, viewBookingScreen_Dialog):
                _translate = QtCore.QCoreApplication.translate
                viewBookingScreen_Dialog.setWindowTitle(_translate("viewBookingScreen_Dialog", "Dialog"))
                self.view_txt.setText(_translate("viewBookingScreen_Dialog", "VIEW BOOKING"))
                self.backBtn.setText(_translate("viewBookingScreen_Dialog", "BACK"))
                self.viewNowBtn.setText(_translate("viewBookingScreen_Dialog", "VIEW NOW"))
                self.dateBookedLabel.setText(_translate("viewBookingScreen_Dialog", "Date Booked"))
                self.dropOffAddresslLabel.setText(_translate("viewBookingScreen_Dialog", "Drop Off Address"))
                self.pickUpDateLabel.setText(_translate("viewBookingScreen_Dialog", "Pick Up Date"))
                self.pickUpAddressLabel.setText(_translate("viewBookingScreen_Dialog", "Pick Up Address"))
                self.pickUpTimeLabel.setText(_translate("viewBookingScreen_Dialog", "Pick Up Time"))
                self.viewSlogan.setText(_translate("viewBookingScreen_Dialog", "VIEW YOUR BOOKING NOW!!"))
                self.bookingIdLabel.setText(_translate("viewBookingScreen_Dialog", "Booking ID"))
                self.viewInstruction.setText(_translate("viewBookingScreen_Dialog",
                "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">To View your Booking,"
                " enter your Booking ID then click the <br/>View Now button.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewBookingScreen_Dialog = QtWidgets.QDialog()
    ui = Ui_viewBookingScreen_Dialog()
    ui.viewBookingScreen_setupUi(viewBookingScreen_Dialog)
    viewBookingScreen_Dialog.show()
    sys.exit(app.exec_())
